### ISSUE TITLE
missing mod client side

### ISSUE THREAD

**Issue by the-webguys** [ErdbeerbaerLP/Discord-Chat-Integration#106]
Hello

I am receiving the following error:

```[FML]: Attempting connection with missing mods [discordintegration] at CLIENT```

This mod is on the server and or so i thought a server only mod. Any-who i added to my custom twitch pack and it doesn't get loaded and still responds with the same error. Any thoughts?

mod version: `DiscordIntegration-mc1.12.2-3.0.5.jar`

**Comment by ErdbeerbaerLP** [comment]
It it only logs it but still joins the server it is completely normal (as the server has one more mod than the client)
