### ISSUE TITLE
Incorrect placeholder for "ingame_discord_msg" option (also a small request)

### ISSUE THREAD

**Issue by katubug** [ErdbeerbaerLP/Discord-Chat-Integration#11]
Hi! Small issue I found. The config says this:

```
# This is what will be displayed ingame when someone types into the bot´s channel
        # PLACEHOLDERS:
        # %name% - The username
        # %id% - The user ID
        # %msg% - The Message
        S:INGAME_DISCORD_MSG=§6[§5DISCORD§6]§r <%user%> %msg%
```

Currently, it prints the discord username instead of the nickname, which I was hoping to change. I thought perhaps changing it to `<%name%>` would do the trick, but it turns out that's not actually a proper variable, and it just prints to chat as `<%name%>`. So you may want to change the placeholders.

Also, if it's possible, I'd really like to have the name print as their Discord server nickname, as most of us know each other by name and not by xXpro_reapsXx :P

Also, since I see you have a lot of FTB Utilities support, would it be possible to have the name printed to Discord be someone's FTBU `/nick` set name, instead of their Minecraft username? It's not as important, but it'd be a nice feature.

Thanks for your time, sorry for making two issues in such quick succession!

**Comment by ErdbeerbaerLP** [comment]
The /nick feature is already about to release. (https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/issues/9)
![image](https://user-images.githubusercontent.com/27149563/67631223-9bd7c180-f893-11e9-85e0-b3ea13adc5d5.png)
But that placeholder bug and the /say or /me commands I will do now
/list is a default command I added

**Comment by ErdbeerbaerLP** [comment]
Yo ucan download it from [here](http://api.erdbeerbaer.tk/dcintegration-1.1.1-1.12.jar) now. Curseforge needs some more time...

**Comment by katubug** [comment]
Thanks! Updating now :)
