### ISSUE TITLE
[Suggestion] Emojiful

### ISSUE THREAD

**Issue by YOYOK9** [ErdbeerbaerLP/Discord-Chat-Integration#125]
The mod Emojicord adds well emojis to minecraft chat. However the discord chat seems them as their base commands, ie a 😄 in minecraft will appear as  :smile : in discord. And the emoji in discord shows up as a square [] in minecraft. 

Unless I completely missed something in the config (100% possible) would something like this be possible? Would be really neat.

Mod: https://www.curseforge.com/minecraft/mc-mods/emojicord

**Comment by ErdbeerbaerLP** [comment]
This feature should already be implemented for 1.14 and 1.15. Won't backport it to 1.12 and, as there is no emojicord for 1.16, i can't port it to 1.16 right now. If you are on 1.15 and it does not work, please comment and I re-open this

**Comment by YOYOK9** [comment]
I am so sorry, I linked the wrong mod all together. The mod is Emojiful NOT emojicord. My bad. I am on 1.16.3 currently. They are so close name wise.. 
https://www.curseforge.com/minecraft/mc-mods/emojiful

**Comment by ErdbeerbaerLP** [comment]
Oh, great to know there is an up-to-date alternative. Adding to to-do list

**Comment by ErdbeerbaerLP** [comment]
I see what is happening here. This also counts as bug, as I was already converting emotes into thier text form (  :smile:  -> `:smile:` ). But it seems that JDA does not count most default emoji as an Emoji object inside of the message. It rather uses unicode symbols which get displayed as [] ingame.

This is what I could produce with an library which tries to convert the unicode emotes back into text:
![ ](https://cdn.discordapp.com/attachments/586258622439489536/770774505520889876/unknown.png)

**Comment by ErdbeerbaerLP** [comment]
Going to close this as it now is halfway implemented in the latest 1.16 beta release and I can't really go any step further unless I **manually** replace every single emote with the text version of it
