### ISSUE TITLE
[BUG] Very long delay on server start / Cannot start server

### ISSUE THREAD

**Issue by DrewSin-4** [ErdbeerbaerLP/Discord-Chat-Integration#128]
**What happened?**
- ~~JDA is not updated~~ Bot is missing Server Members Intent causing servers to be unable to startup

**Steps to reproduce**
- install dcintegration
- start server
- wonder why server isn't starting

**Version**
-
- [X] 1.12
- [X] 1.14
- [X] 1.15
- [X] 1.16

Mod version _any_

__**Solution**:__
-
Enable Server Members Intent on your bot configuration page (the one on https://discord.com/developers/applications )

**Comment by jasongaunt** [comment]
@DrewSin-4 @ErdbeerbaerLP hi both, this is also affecting us too.

FTB Relevations 1.12.2 dedicated server with 1.1.18 dcintegration plugin. 

Log snippet: https://pastebin.com/TqHasLnr

Server hangs at this point and does not continue after 5 minutes. Update check is set to false in the config.

**Note:** This has worked on a Windows server just fine yesterday, however I just migrated my server to a Linux host (with the Oracle Java Runtime environment jre1.8.0_271) and I can no longer start my server up.

**Comment by ErdbeerbaerLP** [comment]
I will update it as soon as I can. Update will be pushed today

**Comment by jasongaunt** [comment]
@ErdbeerbaerLP wub woo! ♥

**Comment by ErdbeerbaerLP** [comment]
Interestingly, I just looked at that log and it _looks like_ it works just fine.

**Comment by shikyo13** [comment]
![image](https://user-images.githubusercontent.com/10563401/97315191-74189200-1836-11eb-871e-f1388894db7d.png)
Can confirm Enigmatica 2 Expert server with DC Integration hanging at the same point

**Comment by ErdbeerbaerLP** [comment]
https://www.curseforge.com/minecraft/mc-mods/dcintegration/download/3094425

**Comment by shikyo13** [comment]
This appears to still be occurring in DiscordIntegration-1.1.19 (MC 1.12) . https://docs.google.com/document/d/1cadO9SS_5gXCu5yQq6s-I0wf4894yHiRBNwfMDplhmA/edit?usp=sharing ( log too long for pastebin / hastebin because E2E )
![image](https://user-images.githubusercontent.com/10563401/97331157-0de83b00-1847-11eb-93f9-85dcb26ad9b4.png)

**Comment by Yamza** [comment]
Seems to still not be loading passed this:
https://i.imgur.com/X1gGKlZ.png

**Comment by ErdbeerbaerLP** [comment]
🤔 Weird. Maybe discord has an bad time currently (even tho discord itself seems responsive)

**Comment by BodiwNz** [comment]
Hey there! I seem to be experiencing this issue as well. 
Im part of a community with 11 servers and all using DC-Integration seem to be having the issue,from 1.12.2 to 1.16.3
Also just tried with different modpacks on 1.12.2 and none seemed to boot with the 1.1.9 fix 
From our perspective, more or less when this bug report was started, the issues couldnt launch properly for no reason at all,and all logs end with the JDA as well . 
Images are : 
 -First : Proof of several servers
 -Second : las debug lines of the "Revelations" server with 1.1.9 patch
Was any other material needed, im more than happy to provide it 
![Captura](https://user-images.githubusercontent.com/58666162/97331935-35a4c680-187a-11eb-8b11-a4b87bc58ba7.PNG)
![Captura](https://user-images.githubusercontent.com/58666162/97332493-cda2b000-187a-11eb-81c7-427e987b31ad.PNG)

**Comment by shikyo13** [comment]
> 
> 
> 🤔 Weird. Maybe discord has an bad time currently (even tho discord itself seems responsive)

Could be but status page reports no major issues https://discordstatus.com/ . Everyone in my community loves this mod, hoping this can be resolved <3 .

**Comment by ErdbeerbaerLP** [comment]
reopening this.

[1.16.3] Can you try if this version works (_**NOTE**_: Unreleased **alpha** version with **NEW CONFIG (requires re-configuration)**. New config file is Discord-Integration.toml. I don't seem to have any issues with this one right now.

To install, drop the file into the mods folder and remove the .zip extension (don't unzip!)
[dcintegration-2.0.0-1.16.jar.zip](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5446706/dcintegration-2.0.0-1.16.jar.zip)

*when does github finally support uploading jars directly here?*

**Comment by BodiwNz** [comment]
Regardi

> reopening this.
> 
> [1.16.3] Can you try if this version works (_**NOTE**_: Unreleased **alpha** version with **NEW CONFIG (requires re-configuration)**. New config file is Discord-Integration.toml. I don't seem to have any issues with this one right now.
> 
> To install, drop the file into the mods folder and remove the .zip extension (don't unzip!)
> [dcintegration-2.0.0-1.16.jar.zip](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5446706/dcintegration-2.0.0-1.16.jar.zip)
> 
> _when does github finally support uploading jars directly here?_

Regarding this,the server seems to have booted ,is responsive, /say hello works etc... yet im getting this issue several times 
![Captura](https://user-images.githubusercontent.com/58666162/97334599-39861800-187d-11eb-87c9-6135420ae31b.PNG)

**Comment by BodiwNz** [comment]
> > reopening this.
> > [1.16.3] Can you try if this version works (_**NOTE**_: Unreleased **alpha** version with **NEW CONFIG (requires re-configuration)**. New config file is Discord-Integration.toml. I don't seem to have any issues with this one right now.
> > To install, drop the file into the mods folder and remove the .zip extension (don't unzip!)
> > [dcintegration-2.0.0-1.16.jar.zip](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5446706/dcintegration-2.0.0-1.16.jar.zip)
> > _when does github finally support uploading jars directly here?_
> 
> Regarding this,the server seems to have booted ,is responsive, /say hello works etc... yet im getting this issue several times
> Ill try to setup the bot token and channel now
> ![Captura](https://user-images.githubusercontent.com/58666162/97334599-39861800-187d-11eb-87c9-6135420ae31b.PNG)
> Edit : I do a lot of typos
![Captura](https://user-images.githubusercontent.com/58666162/97336304-27a57480-187f-11eb-9d53-86e6a7fee2a8.PNG)


ATM6 server running and working,most likely I didnt setup the commands properly,but it's running and chatting!

**Comment by ErdbeerbaerLP** [comment]
Interesting 🤔 I just tried it after recompiling and it works for me there. 
![image](https://user-images.githubusercontent.com/27149563/97340932-afda4880-1884-11eb-8ea9-a4e3b7a671b5.png)

In case I changed anything that fixes it, here is another jar file
[dcintegration-2.0.0-1.16.jar.zip](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5447088/dcintegration-2.0.0-1.16.jar.zip)

I could however confirm, that the commands (including help) are not working right now in that version

**Comment by DrewSin-4** [comment]
Unfortunately I can confirm this bug still works with 1.12.2's newest version you just uploaded.

[18:00:26] [Server thread/INFO] [STDOUT]: [de.erdbeerbaerlp.dcintegration.DiscordIntegration:preInit:412]: Loading mod
[18:00:26] [Server thread/INFO] [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[18:00:26] [Server thread/INFO] [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[18:00:26] [Server thread/INFO] [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[18:00:27] [Server thread/INFO] [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
[18:00:27] [Server thread/INFO] [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation MDCAdapter implementation.
[18:00:27] [Server thread/INFO] [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[18:00:28] [Server thread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [Server thread] INFO JDA - Login Successful!
[18:00:28] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket

Server gets stuck with that ^

**Comment by CrypticSiri** [comment]
This issue also appears to be occurring on version 1.15.2. I've had to remove the Discord Integration config so that my server can start without the mod attempting to connect to Discord. I don't know how much help this'll be, seeing as it's pretty much exactly what everyone else is experiencing, but here's my log: https://hastebin.com/coxubowiji.yaml

**Comment by StoneMasons4106** [comment]
I can confirm this is also happening for me in 1.15.2. I'm assuming you're aware and a 1.15.2 release is coming soon.

**Comment by AnodeCathode** [comment]
Discord decided to start enforcing a new bot permission/feature today from the looks of it.  I had 3 minecraft servers stop communicating with my bot.  I had to go into the bot and enable "SERVER MEMBERS INTENT" in order to fix our issue.

**Comment by ErdbeerbaerLP** [comment]
oh, ok. I will add this to the curseforge description

**Comment by StoneMasons4106** [comment]
Totally worked with the Server Members Intent. Thanks for adding that, all back to normal for 1.15.2.

**Comment by coffeeordeath** [comment]
> Discord decided to start enforcing a new bot permission/feature today from the looks of it. I had 3 minecraft servers stop communicating with my bot. I had to go into the bot and enable "SERVER MEMBERS INTENT" in order to fix our issue.

how did you do this?

**Comment by BodiwNz** [comment]
Im not expert but....

> > Discord decided to start enforcing a new bot permission/feature today from the looks of it. I had 3 minecraft servers stop communicating with my bot. I had to go into the bot and enable "SERVER MEMBERS INTENT" in order to fix our issue.
> 
> how did you do this?

![Uploading Captura.PNG…]()

**Comment by BodiwNz** [comment]
> > Discord decided to start enforcing a new bot permission/feature today from the looks of it. I had 3 minecraft servers stop communicating with my bot. I had to go into the bot and enable "SERVER MEMBERS INTENT" in order to fix our issue.
> 
> how did you do this?

Im no expert,but...
![Captura](https://user-images.githubusercontent.com/58666162/97364494-70235900-18a4-11eb-89e7-974259d4f4ad.PNG)

**Comment by chunkedelement** [comment]
Thanks for this fix I referenced to the other mod dev as we were having the same issue. Much appreciated again.

**Comment by DrewSin-4** [comment]
> > > Discord decided to start enforcing a new bot permission/feature today from the looks of it. I had 3 minecraft servers stop communicating with my bot. I had to go into the bot and enable "SERVER MEMBERS INTENT" in order to fix our issue.
> > 
> > 
> > how did you do this?
> 
> Im no expert,but...
> Edit : its the botom one, im still dumb to this day
> ![Captura](https://user-images.githubusercontent.com/58666162/97364494-70235900-18a4-11eb-89e7-974259d4f4ad.PNG)

Enabled this, and the server still gets stuck on connecting to web socket lol

**Comment by jasongaunt** [comment]
Hi all,

I can confirm after enabling the **Presence Intent** box the original dcintegration 1.12.2-1.1.18 plugin works again without upgrade. Thank you @AnodeCathode and @BodiwNz for instructions.

@ErdbeerbaerLP even though this ended up being Discords fault, we all really appreciate your fast response in attempting to fix this, you rock 👍

Moving forward, it may be worth putting a new page on the Wiki with the above instructions. I don't think Bodi will mind if you reuse his screenshot. I think then you can mark this issue as resolved.

**Comment by austins** [comment]
I ran into this issue of the server crashing and not able to restart completely with dcintegration 1.1.18. Updating to 1.1.19 didn't fix it. I can confirm that enabling "Server Members Intent" fixed it (along with the 1.1.19 update, although the fix may be independent).

![image](https://user-images.githubusercontent.com/1623983/97473945-c7f3ab80-1908-11eb-8fce-42d3c5c06b96.png)
