### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by CyaNox** [ErdbeerbaerLP/Discord-Chat-Integration#13]
https://paste.dimdev.org/coyayuwako.mccrash

This happens on startup very early on. I was trying to do a initial run so that the mod creates the configuration ... but it fails to do so.

**Comment by ErdbeerbaerLP** [comment]
Since curseforge takes some time, you can download it [here ](http://api.erdbeerbaer.tk/dcintegration-1.1.3-1.12.jar) or wait for curseforge.

**Comment by CyaNox** [comment]
Works great now thanks.
