### ISSUE TITLE
[BUG] Bot wont work with webhook=true

### ISSUE THREAD

**Issue by Daxtillion** [ErdbeerbaerLP/Discord-Chat-Integration#132]
**What happened?**
-After the Discord API change and updating the mod to the new version **(dcintegration-1.1.19-1.12)** and making sure it was configured correctly as per the new setup instructions (enabled server members intent). with Webhook=false it prints to the server chat discord channel without the correct user chat formatting (as intended) however with webhook=true (in order to get the correct chat formatting) it wont register in the server chat at all. 

**What it looks like after the update (working with Webhook=false)**
![image](https://user-images.githubusercontent.com/8362507/97643317-716aa680-1a9b-11eb-8fc8-54e1482ab083.png)

**What should happen?**
-**What it used to look like before the update with webhook=true (which now no longer prints anything to the server chat)**
![image](https://user-images.githubusercontent.com/8362507/97643408-ad057080-1a9b-11eb-87f2-1f528b2629a4.png)

**Steps to reproduce**
- 
- 

**Version**
-
**- [x ] 1.12**
- [ ] 1.14
- [ ] 1.15

Mod version _1.1.19_

**Config file**
- 
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
-

**Additional info**

-

**Comment by KangyKSLG** [comment]
Webhooks not working for me either unfortunately :(

**Comment by ErdbeerbaerLP** [comment]
Does this work when downgrading the version again and still having the intent enabled? It should work. The one key change in the new version was updating JDA (which I thought fixed it, but then it was something else), and implementing **webhook caching** (this likely broke that)

**Comment by KangyKSLG** [comment]
I've just tested it and all works fine on the previous version, webhooks and all

**Comment by Daxtillion** [comment]
Can confirm it works with the 1.1.18 release and the new bot perms :)
