### ISSUE TITLE
[BUG]  Say command bug

### ISSUE THREAD

**Issue by gjtjwnsdl** [ErdbeerbaerLP/Discord-Chat-Integration#133]
**What happened?**
- say command in server aren't shown in discord

**What should happen?**
- 

**Steps to reproduce**
- 
- 

**Version**
-
- [x] 1.12
- [ ] 1.14
- [ ] 1.15

Mod version _0.0.0_

**Config file**
- [https://drive.google.com/file/d/11PAHeB-GSA_AbWNHWjqjytbMybbBAUGE/view?usp=sharing](url)

*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
-

**Additional info**

-**linux**, catserver newest version

**Comment by ErdbeerbaerLP** [comment]
Will investigate this. 

Did you install mods that change anyhting on serverside chat? If yes, please tell me which.

Also (found by me) Another say bug. You can send /say and /me messages to discord without having permission to even use the command (1.14+).

**Comment by gjtjwnsdl** [comment]
I installed
- FTB Quest
- FTBLib
- FTB Utilities
- Waystone
- Phosphor
- Hwyla
- ProgressiveBosses
- BetterFPS
- FoamFix
- Vanillafix
