### ISSUE TITLE
[BUG] Crash on startup DiscordIntegration-2.0.0 (MC 1.16.3)

### ISSUE THREAD

**Issue by waggz81** [ErdbeerbaerLP/Discord-Chat-Integration#134]
**What happened?**
- Added DiscordIntegration-2.0.0 (MC 1.16.3) mod to Valhelsia 3 modpack and server crashes with error on startup

**What should happen?**
- Server should start 

**Steps to reproduce**
- Downloaded mod from https://www.curseforge.com/minecraft/mc-mods/dcintegration/files/3099250
- Copied config from https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fgist.githubusercontent.com%252fErdbeerbaerLP%252f2b8e4ad30c14bc2941e0f7de63bcaf62%252fraw%252fDiscord-Integration.toml
- Set bot token, channel id, and admin id in config
- Started server

**Version**
- [x] 1.16.3
- [ ] 1.12
- [ ] 1.14
- [ ] 1.15

Mod version _2.0.0_

**Config file**
- https://pastebin.com/twVMr3MK

**Crash report if available (use https://paste.dimdev.org)**
- https://pastebin.com/rWX8DzMg

**Additional info**

- Fresh install, I have not used this mod before and just tried adding the latest version for 1.16.3. Forge version in this pack is currently on 34.1.25 and I cannot use newer version due to mod incompatibility with Powah.

**Comment by StoneMasons4106** [comment]
I can confirm I get the same error as well.

**Comment by ErdbeerbaerLP** [comment]
I looked at the log. Enable webhook mode (workaround) **or** wait a bit longer, until I release an fix later today

**Comment by waggz81** [comment]
> 
> 
> I looked at the log. Enable webhook mode (workaround) **or** wait a bit longer, until I release an fix later today

Thanks, the webhook works.
