### ISSUE TITLE
Filtering of colors in message to discord

### ISSUE THREAD

**Issue by CyaNox** [ErdbeerbaerLP/Discord-Chat-Integration#14]
This:
![image](https://user-images.githubusercontent.com/211381/68270897-3b990a80-005f-11ea-9acb-e32048088d0a.png)

Looks kinda meh in discord but nice ingame.

You could maybe filter the colors out and possibly transform the underline and bold minecraft codes into discords ones?

**Comment by ErdbeerbaerLP** [comment]
I might add a config entry doing this. I know there is some mod which converts discord formatting to minecraft. I need to find out which one is doing that. (It Is in a modpack I made)

**Comment by CyaNox** [comment]
Works great. Thanks!
