### ISSUE TITLE
[BUG] continuous NPE in sendMessage

### ISSUE THREAD

**Issue by cpw** [ErdbeerbaerLP/Discord-Chat-Integration#141]
**What happened?**
- Getting repeated NPEs in sendMessage

**What should happen?**
- it should succeed or fail. not spam.

**Steps to reproduce**
- Don't know, bot stopped responding on discord and started spamming NPEs

**Version**
- [x] 1.16.3
- [ ] 1.12
- [ ] 1.14
- [ ] 1.15

Mod version _2.0.1_

**Config file**
- nothing special

**Crash report if available (use https://paste.dimdev.org)**
- None. Just lots of NPEs.

**Additional info**
Log file. Looks like JDA decided to OOM? WTF?!

https://gist.github.com/cpw/a941432758bf16bf6c33a35ffebb26b9

**Comment by ErdbeerbaerLP** [comment]
Semilar problem, just without that out of memory error there, was on the MMD discord. The problem was the disabled server members intent. Did you enable it on the bot at  https://discord.com/developers/applications ?

**Comment by cpw** [comment]
Yes, I did that the other day when it started causing problems.

**Comment by Claxtastic** [comment]
Same

**Comment by ErdbeerbaerLP** [comment]
This _should_ be fixed by an workaround in version 2.0.2 on CurseForge now
Keeping this open as it only is an workaround
