### ISSUE TITLE
Console spam/ Server restart taking forever 

### ISSUE THREAD

**Issue by TheMeowstardcat** [ErdbeerbaerLP/Discord-Chat-Integration#142]
Issues occuring with RAD ( Roguelike adventures and Dungeons ) server. 
Using dcintegration version 1.1.10-1.12.2

Anytime server restart's this is making server hang for long period of times when restarting. Also console is getting spammed with this 
![issue](https://user-images.githubusercontent.com/60239829/98163380-c0a44300-1eb0-11eb-9f3b-8a2c4f6a1c80.PNG)

**Comment by ErdbeerbaerLP** [comment]
Did you enable Server Members Intent? If not enable this first.

The stop/restart freeze tho is still as known bug for older versions than 2.0.0 and will be fixed after the 2.0.x is stable enough.

Also, for 1.12 make sure to disable channel description! This is no longer supported.

**Comment by TheMeowstardcat** [comment]
> 
> 
> Did you enable Server Members Intent? If not enable this first.
> 
> The stop/restart freeze tho is still as known bug for older versions than 2.0.0 and will be fixed after the 2.0.x is stable enough.
> 
> Also, for 1.12 make sure to disable channel description! This is no longer supported.

Yes I do have server members Intent enabled. I just changed( MODIFY_CHANNEL_DESCRIPTRION=false ) to false. Should I disregard the console spam like in the image then?

**Comment by ErdbeerbaerLP** [comment]
That spam was caused by the channel description

**Comment by ErdbeerbaerLP** [comment]
It updated more often (i think every 2 seconds or so) than discord now allows (2 times in 10 minutes)

**Comment by ErdbeerbaerLP** [comment]
Also (just an hint) you can update to Discord Integration version 1.1.18 (1.1.19 seems to have an webhook bug)

**Comment by TheMeowstardcat** [comment]
> 
> 
> It updated more often (i think every 2 seconds or so) than discord now allows (2 times in 10 minutes)

Thank you. I appreciate the help.

**Comment by TheMeowstardcat** [comment]
> 
> 
> Also (just an hint) you can update to Discord Integration version 1.1.18 (1.1.19 seems to have an webhook bug)

I have tried the 1.1.18 version but for some reason it crashes the server. only version I can use is the 1.1.10
here is the latest log 
[latest(4).log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5490451/latest.4.log)

**Comment by ErdbeerbaerLP** [comment]
Ah some other mod uses an older mixin version which got loaded before this new one.then stay at the old version or update all mods and try then

**Comment by TheMeowstardcat** [comment]
> 
> 
> Ah some other mod uses an older mixin version which got loaded before this new one.then stay at the old version or update all mods and try then

Thanks for the advice. It will be easier for me to stay on a older version since I do not know anything how to update a modpack lol. I just host servers for my Discord community. All the issues seem to be resolved again thank you for the help. I'm going to go ahead and close this.
