### ISSUE TITLE
Causing server to not boot.

### ISSUE THREAD

**Issue by Dolinmyster** [ErdbeerbaerLP/Discord-Chat-Integration#146]
Hello,

I added your mod to the FTB Academy 1.4.0 and when I attempt to boot the server, it hangs at the below line and will not boot. I do know currently there appears to be an issue with Discord and embeding things. Not sure if this is related.

this is running forge-1.12.2-14.23.5.2847

[net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-WriteThread]: INFO WebSocketClient - Connected to WebSocket

**Comment by ErdbeerbaerLP** [comment]
Did you enable server members intent?
![Example](https://support.discord.com/hc/article_attachments/360054322951/intents.png)

**Comment by Dolinmyster** [comment]
That was the issue. I'm glad I have this bug here so hopefully someone else can find it later. Thank you for the tip! I must have missed that.
