### ISSUE TITLE
[BUG] Bot doesn't turn on

### ISSUE THREAD

**Issue by BugmanBugman** [ErdbeerbaerLP/Discord-Chat-Integration#147]
**What happened?**
-Bot did not work as planned

**What should happen?**
-It working

**Version**
1.16.4
Mod version _0.0.0_

**Config file**
-https://hatebin.com/cztduivosz
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**

https://hatebin.com/zmvsnecdmf

**Comment by leonx132** [comment]
@BugmanBugman what was the fix?

**Comment by BugmanBugman** [comment]
> @BugmanBugman what was the fix?

I forgot, but I think I wiped my config
