### ISSUE TITLE
Constant error message

### ISSUE THREAD

**Issue by Corbinator333** [ErdbeerbaerLP/Discord-Chat-Integration#149]
I keep getting this error message repeating over and over and over

[m[32m[10:57:34] [OkHttp https://discordapp.com/.../INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [OkHttp https://discordapp.com/...] WARN RateLimiter - Encountered 429 on route /channels/779417527419535370

**Comment by ErdbeerbaerLP** [comment]
1.12?
Disable channel description feature
