### ISSUE TITLE
Commands work in all channels the bot can see[BUG] 

### ISSUE THREAD

**Issue by Ki-Tan2934** [ErdbeerbaerLP/Discord-Chat-Integration#152]
**What happened?**
-commands like, /list work in all channels outside of the set channel

**What should happen?**
-bot should not read or write in them channels

**Steps to reproduce**
- do /list on any channel the bot can see and write to

**Version**
-1.16.4

Mod version dcintegration-2.0.2-1.16.jar

**Config file**
- https://paste.ubuntu.com/p/573yzwXHRK/

**Comment by Ki-Tan2934** [comment]
Looks like a problem with webhooks as it keeps making new ones depending on what channel has been used

**Comment by ErdbeerbaerLP** [comment]
Fixed in latest alpha version (2.0.4)
