### ISSUE TITLE
Option to hide certain commands or server command executions in the log channel [Suggestion]

### ISSUE THREAD

**Issue by Autopoietico** [ErdbeerbaerLP/Discord-Chat-Integration#157]
There are certain commands that are executed automatically for certain panels like Multicraft, if the log channel is active, that channels fill with the same command execution generating spam and making the channel unusable.
In this case, banning the list command or server execute commands can be enough to stop the spam
![image](https://user-images.githubusercontent.com/8708366/100822824-140ea000-3421-11eb-9a91-cecaa48208aa.png)

**Comment by ErdbeerbaerLP** [comment]
I will add that to the next update
