### ISSUE TITLE
[BUG] Sorry, but the bot has no permissions...

### ISSUE THREAD

**Issue by DrToxic** [ErdbeerbaerLP/Discord-Chat-Integration#158]
**What happened?**
- Bot was unable to complete the /tps command.

> Sorry, but the bot has no permissions...
> Add this into the servers ops.json:
>  {
>    "uuid": "8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3",
>    "name": "DiscordFakeUser",
>    "level": 4,
>    "bypassesPlayerLimit": false
>  }

**What should happen?**
- Discord bot should repsond to /tps command.

**Steps to reproduce**
- add json to ops.json 
- restart minecraft
- minecraft clears ops.json
- tried to op DiscordFakeUser, turns out it has a different UUID (removed them from ops again after trying it to see it didn't work)

**Version**
-
- [ ] 1.12
- [ ] 1.14
- [x] 1.16

Mod version _1.3.4_

**Comment by ErdbeerbaerLP** [comment]
About MC clearing the ops.json: This likely happens to invalid content. 

Is there anything before pasting it in? If nothing else than {} or even nothing, paste/ replace it with this instead:
```
{
{
"uuid": "8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3",
"name": "DiscordFakeUser",
"level": 4,
"bypassesPlayerLimit": false
}
} 
```
If it Con tains something, just add it like this:
```
{
{
"uuid": "xyz",
"name": "someone",
"level": 4,
"bypassesPlayerLimit": false
},
{
"uuid": "8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3",
"name": "DiscordFakeUser",
"level": 4,
"bypassesPlayerLimit": false
}
}
```

About using the op command ingame: don't do that. It looks like someone claimed an MC account with that name, but usually it should not cause issues, as the ops.json mainly uses the uuid and, looking at namemc, the uuid is still unused. (do not set UUID to the one on the following website and do not use the /op command for this, as it would allow this player to get OP permissions on your server) 
https://namemc.com/profile/DiscordFakeUser.1

**Comment by DrToxic** [comment]
I was just reading up before hitting the sack, and noticed I missed the comma between the two ops (The bot and myself).
It now works, Thanks. 👍
