### ISSUE TITLE
[BUG] Tagged names do not display properly

### ISSUE THREAD

**Issue by ethosrot** [ErdbeerbaerLP/Discord-Chat-Integration#161]
**What happened?**
A message from a discord user that tags another discord user does not correctly render in-game. Instead of showing the tagged user's name, it shows their ID in brackets (<@!13349881305128191>).
> [ethosrot] hey <@!13349881305128191> are you around?

**What should happen?**
In-game chat should render the tagged user's name instead of their discord ID. Ideally a bolding effect might be applied to the name to convey that a tag happened.
> [ethosrot] hey **@coolguy20** are you around?

**Steps to reproduce**
From discord, tag any other discord user in a message which would normally be sent to in-game chat via Discord Integration.

Forge version: 1.16.3-34.1.42
Mod version: 2.0.2-1.16

**Config file**
[dicfg.toml.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5653855/dicfg.toml.txt)

**Comment by ethosrot** [comment]
Just a follow-up, I did some more testing -- it looks like _role_ names are also not being translated from their IDs if someone in Discord tags a role.

It might be neat for the translated name to follow the color code of the role in Discord too, especially since it looks like some of the code is already there for pulling the color.

**Comment by smallerYeet** [comment]
I have the same issue.
![grafik](https://user-images.githubusercontent.com/68237474/101737599-660c9100-3ac5-11eb-8fc3-cd5182342e82.png)
I wanted to ping a role when the server crashes, but that's not possible

**Comment by ErdbeerbaerLP** [comment]
> I wanted to ping a role when the server crashes, but that's not possible

You can ping a role using <@&[ROLE-ID]>  (ofc replace [ROLE-ID] with an role ID)

You can get it by opening the role menu, right click the role and copy ID (requires development mode enabled in discord client)
