### ISSUE TITLE
[BUG] server crashed when player joined

### ISSUE THREAD

**Issue by BugmanBugman** [ErdbeerbaerLP/Discord-Chat-Integration#166]
**What happened?**
Game crashed when player joined

**What should happen?**
-for it not to crash

**Steps to reproduce**
- have open server with webhook enabled
- player join

**Version**
-
1.16.4
Mod version _2.0.2

**Config file**
-https://hatebin.com/kyovefklcb
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
https://hatebin.com/tmldamdqmj

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment]
Try downloading that file again and test if this happens again. 
Might be an corrupted file or something else caused it to get loaded incompletely

**Comment by MattiBorchers** [comment]
I got a similar error, might be related:

Crash report: [https://pastebin.com/U1uywrHB](https://pastebin.com/U1uywrHB)

**Comment by ErdbeerbaerLP** [comment]
That crash report is helpful (even tho it might be an configuration problem, like an empty channel ID variable)

**Comment by MattiBorchers** [comment]
> That crash report is helpful (even tho it might be an configuration problem, like an empty channel ID variable)

This was my first idea. Here is my config (just masked a bit of the token / channe ID: [https://pastebin.com/mp0RgS3T](https://pastebin.com/mp0RgS3T)

In the "DiscordIntegration-Data" folder there is "LinkedPlayers.json" file that is empty. Maybe is this the cause?

**Comment by ErdbeerbaerLP** [comment]
This file will be empty until an player uses /discord link

**Comment by ErdbeerbaerLP** [comment]
serverChannelID = ""

change it to 

  serverChannelID = "default"

but i will also add some checks that it won't actually crash the server but log an error

**Comment by MattiBorchers** [comment]
Thanks for the fast response.
Sadly this change makes no difference. I still got the server-crash.
I even changed all of the ChannelID to "default" like this:

channelDescriptionID = "default"
serverChannelID = "default"
deathChannelID = "default"
chatInputID = "default"
chatOutputID = "default"

**Comment by ErdbeerbaerLP** [comment]
It should no longer crash for invalid channel IDs when sending messages

I hope the latest update fixed the other issue now (if it was an different one)
If not, simply re-open this and I might find another bug that can cause this.
