### ISSUE TITLE
[BUG] Not the right output in DM's

### ISSUE THREAD

**Issue by DvaVR** [ErdbeerbaerLP/Discord-Chat-Integration#168]
**What happened?**
- This is in DM ![image](https://user-images.githubusercontent.com/71989906/103464514-816d6380-4d34-11eb-8dd2-4a104b78a0a9.png)

**What should happen?**
-I guess display your MC name and the right prefix

**Steps to reproduce**
- I have no idea
- 

**Version**
- 1.16.4
- [ ] 1.12
- [ ] 1.16

**Platform**
-
- [x ] Forge
- [ ] Spigot

Mod version: dcintegration-2.0.9-1.16

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*
[Discord-Integration.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5760753/Discord-Integration.txt)

**Crash report if available (use https://hastebin.com)**
-no crashes

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
Will fix that in the next update
