### ISSUE TITLE
[BUG][1.16.4] JDA Gateway-Worker 1 

### ISSUE THREAD

**Issue by YOYOK9** [ErdbeerbaerLP/Discord-Chat-Integration#171]
**What happened?**
- After server boots fully and players can join, the server just locks up on:

[JDA Gateway-Worker 1]: WARN net.dv8tion.jda.internal.requests.WebSocketClient - Missed 2 heartbeats! Trying to reconnect...

**What should happen?**
- Able to connect to / server doesn't lock up.

**Version**
-
- [ ] 1.12
- [X] 1.16

**Platform**
-
- [X] Forge
- [ ] Spigot

Mod version: 
DiscordInt: 2.0.9-1.16
Forge: 35.1.28

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*
https://pastebin.com/BUgK9TtX

**Crash report if available (use https://hastebin.com)**
-Server doesnt crash just locks up. 
Latest Log: https://gist.github.com/YOYOK9/7bf7a201ae2cd33f1bcf247156bf170b

**Additional info**
- I tried updating to the newest version today, had been using 2.0.2-1.16 with no issues. Other than that nothing else has been changed server wise. Was working just fine 12h ago. Best guess the newest update for discord itself is breaking things...again...

**Comment by ErdbeerbaerLP** [comment]
Sometimes Discord itself also has problems which *could* cause this to happen.
But actually, it should not freeze the whole server.

Try again, maybe it will work now without freezing. If it still freezes, go back to the older working version or wait for the new update

**Comment by YOYOK9** [comment]
It had actually started freezing on the old version first, thought maybe I should try the most up to date version to see if it fixes it. Unfortunately it did not.

**Comment by ErdbeerbaerLP** [comment]
I hope the latest update fixed that now
If not, simply re-open this and I might find another bug that can cause this.

**Comment by QuerGamer** [comment]
I have the **same problem** but only **on** machines with **Debian 9**. On my **Debian 10** machine **and** on **Windows** **no problems**.
