### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mihionmc** [ErdbeerbaerLP/Discord-Chat-Integration#174]
**What happened?**
-console spam

**What should happen?**
-

**Steps to reproduce**
- 
- 

**Version**
-
- [ ] 1.12
- [ x] 1.16

**Platform**
-
- [ x] Forge
- [ ] Spigot

Mod version: 

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-
https://pastebin.pl/view/c009c837
**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
Should be fixed in 2.1.0
