### ISSUE TITLE
Make it so the Discord relays are colour coded

### ISSUE THREAD

**Issue by Osprey4444** [ErdbeerbaerLP/Discord-Chat-Integration#18]
Hi!

This is more so a suggestion rather than an issue.

I would recommend making it so when a discord message is sent and is shown in game the person that sent the messages name is colour coded to their role's colour.

**Comment by ErdbeerbaerLP** [comment]
I just attempted to do that, but since minecraft color codes are very limited and discords are not I couldn't find a way to find the closest minecraft color from an RGB color you have in discord
