### ISSUE TITLE
Custom mcCommands

### ISSUE THREAD

**Issue by Fliberatto** [ErdbeerbaerLP/Discord-Chat-Integration#183]
How to properly add custom commands? I'm trying to get the bot to OP someone. 
I'm using the latest version in a Forge server.

**Comment by ErdbeerbaerLP** [comment]
Here is the default json, but with an /op <player> command added

customCommandJSON = "{\"kick\":{\"adminOnly\":true,\"mcCommand\":\"kick\",\"description\":\"Kicks a player from the server\",\"useArgs\":true,\"argText\":\"<player> [reason]\"},\"stop\":{\"adminOnly\":true,\"mcCommand\":\"stop\",\"description\":\"Stops the server\",\"aliases\":[\"shutdown\"],\"useArgs\":false},\"kill\":{\"adminOnly\":true,\"mcCommand\":\"kill\",\"description\":\"Kills a player\",\"useArgs\":true,\"argText\":\"<player>\"}**,\"op\":{\"adminOnly\":true,\"mcCommand\":\"op\",\"description\":\"OPs a player\",\"useArgs\":true,\"argText\":\"<player>\"}**}"

**Comment by Fliberatto** [comment]
Thank you!
