### ISSUE TITLE
[BUG] Ratelimit spam

### ISSUE THREAD

**Issue by NFLD99** [ErdbeerbaerLP/Discord-Chat-Integration#185]
**What happened?**
spams this in console
[04:24:17] [OkHttp https://discordapp.com/.../INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [OkHttp https://discordapp.com/...] WARN RateLimiter - Encountered 429 on route /channels/*REDATCTED*
https://i.imgur.com/hGvwAhX.png

**What should happen?**
it shouldn't spam that in console

**Steps to reproduce**
Start your server
view console

**Version**
- [ ] 1.12.2

**Platform**
- [ ] Forge

Mod version: 
dcintegration-1.1.18-1.12

**Config file**
https://gist.githubusercontent.com/NFLD99/a2e1e63490edb3c45d3cbe3af83af7c7/raw/a55f0dd954ceec1ce4911a8aa2df20b046b4f20f/Discord-Integration.cfg

**Crash report if available (use https://hastebin.com)**
N/A

**Additional info**
N/A

**Comment by ErdbeerbaerLP** [comment]
set `B:MODIFY_CHANNEL_DESCRIPTRION=` to false

**Comment by NFLD99** [comment]
oh okay ill try that, is there another way for it to post uptime? {maybe on the bots status}

**Comment by NFLD99** [comment]
Seems that feature is broken is there another way to provide uptime TPS and playercount that's kept updated?
