### ISSUE TITLE
[BUG] Unable to link MC and Discord accounts

### ISSUE THREAD

**Issue by jonman364** [ErdbeerbaerLP/Discord-Chat-Integration#187]
**What happened?**
- /link #
- Unknown command

**What should happen?**
- Accounts linked

**Steps to reproduce**
- Type /discord link in Minecraft
- Paste command into Discord
- `Unknown Command, try /help for a list of commands`

**Version**
-
- [ ] 1.12
- [x] 1.16

**Platform**
-
- [x] Forge
- [ ] Spigot

Mod version: 
2.1.0-1.16

**Config file**
- Only changed `botToken` and `botChannel`

**Additional info**
- Fresh Forge 1.16.4-35.1.37 install with only mod being dcintegration
- `/help`, `/list`, and `/uptime` commands and bidirectional chat work

**Comment by goethenorris** [comment]
Typing     /discord link     into Minecraft gives "this subcommand is disabled"
Typing     /discord link     prompts unknown command
Any other command quotes user not OP althoug ops file has been modified and manually op through console

**Comment by jonman364** [comment]
I guess I always have to go the hard route.  Reading through the code I noticed that link is a DM command.  Going back and reading the response from `/discord link` closer I saw that it indeed says "Send this command as a **direct message** to the bot..."

DM-ing the bot works as expected.

**Comment by MoXAriApph** [comment]
Necrobumping here, this bug is hitting us on our 1.18.2 server, sending command in DM, sending in channel it's linked to, etc. does not work whatsoever, no reaction from the bot whatsoever.

**Comment by Gunner76th** [comment]
> Necrobumping here, this bug is hitting us on our 1.18.2 server, sending command in DM, sending in channel it's linked to, etc. does not work whatsoever, no reaction from the bot whatsoever.

1.12.2 and 1.18.2 are broken due to changes in bot slash command permissions. Because of this, all commands other than /kill no longer work until the bot's code is updated to the new permissions system method.

**Comment by MoXAriApph** [comment]
> 

Oh rip, will be waiting for that, as a heads up for anyone rn, using the Webhook works instead
