### ISSUE TITLE
[BUG] Default Advancement message lines end in a \

### ISSUE THREAD

**Issue by aaronhowser1** [ErdbeerbaerLP/Discord-Chat-Integration#189]
**What happened?**
![](https://cdn.discordapp.com/attachments/801816433993711657/802718148683759637/unknown.png)

**What should happen?**
Not that

**Steps to reproduce**
Get an advancement
Look at it in Discord

**Version**
-
- [ ] 1.12
- [x] 1.16

**Platform**
-
- [x] Forge
- [ ] Spigot

Mod version: 
2.0.2

**Config file**
https://pastebin.com/i6ANf1Sw
-

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
I thought I fixed that default message.

Change 
`  advancementMessage = "%player% just made the advancement **%name%**\\\n_%desc%_"`
to
`  advancementMessage = "%player% just made the advancement **%name%**\n_%desc%_"`

**Comment by ErdbeerbaerLP** [comment]
Closing as I actually fixed that in an newer released version

*you still need to change the config entry*
