### ISSUE TITLE
[BUG] 1.16.5 server crash on load

### ISSUE THREAD

**Issue by SDUBZ** [ErdbeerbaerLP/Discord-Chat-Integration#198]
**What happened?**
-crashed on load

**What should happen?**
-
load normally
**Steps to reproduce**
- load with versions available 
- 

**Version**
-
- [ ] 1.12
- [*] 1.16

**Platform**
-
- [*] Forge 1.16.5-36.0.10
- [ ] Spigot

Mod version: 
dcintegration-2.1.0-1.16.jar
**Config file**
- 
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-
[crash-2021-01-30_03.37.39-server.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/5897638/crash-2021-01-30_03.37.39-server.txt)

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
I would check your config file (if it is an config problem it is likely some channel ID is not set to anything or an invalid one)

**Comment by SDUBZ** [comment]
okay i will double check with virtua server, but i noticed no config file was generated

**Comment by superfishy07** [comment]
I just had this same issue on a brand new server.  Modpack is [Brass](https://www.curseforge.com/minecraft/modpacks/brass/files/3174371), on CurseForge, and it was the first launch with the dcintegration mod included. I used the same version as the original submitter

No config was generated, I was running it this first time to get the config, to add my bot and channel IDs.
Is there a temp config I can try adding to see if that fact that the config is missing is the issue?

Thanks, this is a great mod!

**Comment by superfishy07** [comment]
An update: I copied over a config file from and Enigmatica6 server, which uses the same Discord-Integration jar, but works.  When the config file existed, the mod loads properly.

Modpack Brass v0.4.0a uses forge version 36.0.1
Modpack Enigmatica6 v0.3.6 uses forge version 35.1.36

Not sure if the above helps at all

**Comment by SDUBZ** [comment]
i fixed the issue now everything is working fine
