### ISSUE TITLE
Allow commands to be used in a separate channel.

### ISSUE THREAD

**Issue by Osprey4444** [ErdbeerbaerLP/Discord-Chat-Integration#20]
Hi,

I have a suggestion, allowing commands to be used in a different channel which can be defined within the config, this would be useful for servers which use one dedicated channel to sync multiple server chats as !list would spam the chat giving players on the servers a spammed chat.

**Comment by ErdbeerbaerLP** [comment]
Looks like this will take a bit longer to properly implement

**Comment by Osprey4444** [comment]
That’s not an issue! It’d just be useful for servers with a bot-commands channel or such to maintain some stability.

**Comment by ErdbeerbaerLP** [comment]
Added in next update (but still beta!) custom commands can have multiple channel IDs and the built in commands only have the option for one ID or everywhere
