### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NimbusFox** [ErdbeerbaerLP/Discord-Chat-Integration#202]
**What happened?**
- The discord channel description does not update when the server is running

**What should happen?**
- The discord channel description should update every 2000 milliseconds (2 seconds)

**Steps to reproduce**
- Launch server
- Look at discord channel's description
- It will show the initial description when launched but then not update (It does update when Server is starting and when it is shutdown)

**Version**
-
- [x] 1.12

- [ ] 1.16

**Platform**
-
- [x] Forge
- [ ] Spigot

Mod version: 1.1.18

**Config file**
- https://pastebin.com/WZaLQNds

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
This feature is no longer supported, as Discord only allows two changes per 10 Minutes
