### ISSUE TITLE
[Suggestion] /ignore command in game.

### ISSUE THREAD

**Issue by Osprey4444** [ErdbeerbaerLP/Discord-Chat-Integration#21]
**What you want to be added?**

Hi! I have another suggestion (Sorry for all the suggestions!) a command such as /ignore for players to use ingame or /dcdisable to not get relayed messages from the Discord if they wanted to disable it as some players may not like the spam if it is a heavily populated or talkative server such as mine.

I've had quite a few players request this.

**Comment by ErdbeerbaerLP** [comment]
Added in next update. Syntax: /discord ignore
