### ISSUE TITLE
[Suggestion] Don't disable the mod in single player.

### ISSUE THREAD

**Issue by Rensik** [ErdbeerbaerLP/Discord-Chat-Integration#22]
I've been looking for a discord chat mod to link my modpacks together. However, yours is the only one that even remotely works in 1.12. I attempted to utilize the mod, have my discord set up and ready and everything, but the mod fails to load in Single Player. I checked my logs and found it gets disabled completely. Maybe don't do this and have it not work till LAN is opened?

**Comment by ErdbeerbaerLP** [comment]
If it would load in singleplayer it would just not do anything. For it to work in singleplayer I would have to implement much much more. Since this mod is made for use on servers, I will not do this.

**Comment by Rensik** [comment]
If this loaded in single player, then modpack players could converse with other modpack players through a modpack discord rather than requiring players to be on a server..
