### ISSUE TITLE
[BUG] Server hangs with messages send to discord

### ISSUE THREAD

**Issue by Naxanria** [ErdbeerbaerLP/Discord-Chat-Integration#23]
**What happened?**
Discord was having issues so the messages could take a while to get through. The server hanged every time that a message was send to discord (chat/advancement etc)

**What should happen?**
The server shouldnt have to wait for the message to arrive at Discord's end, and should not hang waiting.

**Steps to reproduce**
Have discord laggy and say something in minecraft chat

**Version**
- 1.14

Mod version 1.1.5

**Comment by ErdbeerbaerLP** [comment]
Known thing because of yesterday. I am investigating on how to fix this
