### ISSUE TITLE
[BUG] Says %player% instead of player name.

### ISSUE THREAD

**Issue by lukasdeveloper** [ErdbeerbaerLP/Discord-Chat-Integration#25]
**Version**
-
- [ ] 1.12
- [x] 1.14

Mod version: DiscordIntegration-1.1.8 (MC 1.14)

https://lukasdev.xyz/ss/0QdUnused.png

**Comment by ErdbeerbaerLP** [comment]
Looks like an ingame message. You must use %user% there.
See [this line](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/blob/1e8f825e5fb9a82791724eb43406de5ac6f2f92a/src/main/java/de/erdbeerbaerlp/dcintegration/Configuration.java#L146) where I define the config setting. Add an new comment if that does not work too

**Comment by lukasdeveloper** [comment]
Apparently that's the default config. Thanks :)
