### ISSUE TITLE
2 way server chat not working Not sure if intended or not

### ISSUE THREAD

**Issue by SkinnySkelly** [ErdbeerbaerLP/Discord-Chat-Integration#26]
I have 2 servers setup one is 1.12.2 and one is 1.14.4 everything is setup perfectly and messages and can sent from both servers to discord and discord messages to the servers. the issue seems to be when a player from the 1.12.2 server says something the person on the 1.14.4 server does not see the message. only on discord they see it. I'm guessing its cause the messages show up as bot messages on discord and the mod ignores these messeges since it would create an infinite loop of some sort I would presume. I was wondering if there is some sort of work around to get these 2 servers to be able to talk to each other.
Example of what im talking about:
player on 1.12.2 server: HI
discord bot: HI
player on 1.14.4 server receives no response from the player on the 1.12.2 server just on the discord app itself.

person replying on discord: Hello
both servers: Hello

**Comment by ErdbeerbaerLP** [comment]
I prevented webhook messages and messages from the same bot to show up. If you have ONE bot set up form both that won't show up on the other one

**Comment by SkinnySkelly** [comment]
ohh ok so make a 2nd bot and disable webhooks and I should be good to go?

**Comment by ErdbeerbaerLP** [comment]
It should, if not add an new comment here

**Comment by SkinnySkelly** [comment]
That Worked. Thanks for the EXTREMELY fast reply
