### ISSUE TITLE
[BUG] 1.1.8 (MC 1.12)  Doesn't announce in channel

### ISSUE THREAD

**Issue by kreezxil** [ErdbeerbaerLP/Discord-Chat-Integration#27]
The mod starts up and after you see your server is up, you can interact with it in Discord. However, it doesn't announce that it is starting in Discord.

It works perfectly in 1.14.4 tho.

**Comment by ErdbeerbaerLP** [comment]
Are you using webhook mode? If yes, disable it if you want that to show up. Webhooks can not edit messages, that is why it does not send an message when starting but not yet online

**Comment by kreezxil** [comment]
i am not using webhook mode

**Comment by ErdbeerbaerLP** [comment]
Ok, i will investigate and try to fix that

**Comment by kreezxil** [comment]
```json
    ##########################################################################################################
    # webhook
    #--------------------------------------------------------------------------------------------------------#
    # Webhook configuration
    ##########################################################################################################

    webhook {
        # Wether or not the bot should use a webhook (it will create one)
        B:BOT_WEBHOOK=false

        # The avatar to be used for server messages
        S:SERVER_AVATAR=https://raw.githubusercontent.com/ErdbeerbaerLP/Discord-Chat-Integration/master/images/srv.png

        # The username of the server
        S:SERVER_NAME=Server
    }
```

**Comment by kreezxil** [comment]
that's the default settings

**Comment by kreezxil** [comment]
these options are set in the general config

```
        # Wether or not the Bot should modify the channel description
        B:MODIFY_CHANNEL_DESCRIPTRION=true

        # If you think the update check is annoying disable this
        B:UPDATE_CHECK=true
```

**Comment by kreezxil** [comment]
odd, it seems to be ignoring my admin id and I did op it on my server in the ops.json

**Comment by kreezxil** [comment]
is any part of this wrong?

```
  {
    "uuid": "8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3",
    "name": "Discord Integartion",
    "level": 4,
    "bypassesPlayerLimit": true
  },
```
other than the typo, oh wait, could be i put a space in there? let me see.

**Comment by kreezxil** [comment]
ok, that space had no bearing on it.

**Comment by kreezxil** [comment]
latest.log if it helps http://paste.ubuntu.com/p/c8gbkRNsXf/
debug.log https://gist.github.com/dd2a3af169088d45403b3fd05ae213d6

**Comment by kreezxil** [comment]
```
        # Custom Channel ID list for the help command. Set to 00 to allow usage from everywhere and to 0 to allow usage from the bots default channel
        S:HELP_CMD_CHANNEL_ID <
            0
         >
```
this setting is not making it be bound to the channel i gave it the general config, it's process /help in all my channels.

this is probably all related

**Comment by kreezxil** [comment]
ok, i gave it an explicit id in all of those settings where you said I could use 00 and 0 and that resolved the issue with trying to parse /help in every channel. All other problems remain.

I'm done bothering you for now. 

cheers!

love the shit out of the 1.14.4 version.

**Comment by ErdbeerbaerLP** [comment]
weird. i just went to test it and it works for me
![image](https://user-images.githubusercontent.com/27149563/71019736-2baf2480-20fb-11ea-9d96-86340c2a536a.png)

**Comment by kreezxil** [comment]
which forge did you use? 2847? I use build 2847 for my 1.12.2 packs. Your
1.14.4 version works perfect for me, so I want to replace Chikachi's 1.12.2
Discord Integration with yours as I feel yours is much better.

**Comment by ErdbeerbaerLP** [comment]
I used 14.23.5.2768. Will now try with the "latest" one

**Comment by ErdbeerbaerLP** [comment]
same result as before 🤔

**Comment by ErdbeerbaerLP** [comment]
But you might want to check your command JSON.

> [14:37:30] [Server thread/INFO] [STDERR]: [de.erdbeerbaerlp.dcintegration.DiscordIntegration:preInit:409]: Failed to login: Not a JSON Object: "{\"kick\":{\"adminOnly\":true,\"mcCommand\":\"kick\",\"description\":\"Kicks a player from the server\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"rank\":{\"adminOnly\":true,\"mcCommand\":\"rank\",\"description\":\"manipulates a players rank\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"ban\":{\"adminOnly\":true,\"mcCommand\":\"ban\",\"description\":\"ban a player\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"op\":{\"adminOnly\":true,\"mcCommand\":\"op\",\"description\":\"op a player\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"deop\":{\"adminOnly\":true,\"mcCommand\":\"deop\",\"description\":\"deop a player\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"gamemode\":{\"adminOnly\":true,\"mcCommand\":\"gamemode\",\"description\":\"change a player's gamemode\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"gamerule\":{\"adminOnly\":true,\"mcCommand\":\"gamerule\",\"description\":\"change a rule on the server\",\"useArgs\":true,\"argText\":\"\\u003crule\\u003e \\u003cvalue\\u003e\"},\"give\":{\"adminOnly\":true,\"mcCommand\":\"give\",\"description\":\"give a player stuff\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e \\u003citemid\\u003e [\\u003cquantity\\u003e]\"},\"weather\":{\"adminOnly\":true,\"mcCommand\":\"weather\",\"description\":\"change the weather\",\"useArgs\":true,\"argText\":\"\\u003cclear|rain|snow\\u003e\"},\"time\":{\"adminOnly\":true,\"mcCommand\":\"time\",\"description\":\"change the time\",\"useArgs\":true,\"argText\":\"\\u003cvalue\\u003e\"},\"kill\":{\"adminOnly\":true,\"mcCommand\":\"kill\",\"description\":\"kill something, might require you to be on the server\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"pardon\":{\"adminOnly\":true,\"mcCommand\":\"pardon\",\"description\":\"pardon a player\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"whitelist\":{\"adminOnly\":true,\"mcCommand\":\"whitelist\",\"description\":\"whitelist a player\",\"useArgs\":true,\"argText\":\"\\u003cplayer\\u003e\"},\"tp\":{\"adminOnly\":true,\"mcCommand\":\"tp\",\"description\":\"use tp on a player, make sure to wipe them clean!\",\"useArgs\":true,\"argText\":\"\\u003csource:player\\u003e \\u003cdestination:player|x y z\\u003e \"},\"dims\":{\"adminOnly\":false,\"mcCommand\":\"forge dimensions\",\"description\":\"list the dimensions on the server\",\"useArgs\":false},\"tps\":{\"adminOnly\":false,\"mcCommand\":\"forge tps\",\"description\":\"get lag based on dimensions and overall\",\"useArgs\":false},\"mods\":{\"adminOnly\":false,\"mcCommand\":\"forge mods\",\"description\":\"list the mods on the server\",\"useArgs\":false},\"entities\":{\"adminOnly\":false,\"mcCommand\":\"forge entity list\",\"description\":\"list the entities on the server\",\"useArgs\":true,\"argText\":\"[\\u003cfilter\\u003e] \"}}"

**Comment by kreezxil** [comment]
the json is fine. like i said it works great in 1.14.4, and it's the same
json

**Comment by kreezxil** [comment]
just leave it open for now but maybe tag it "need more information"
