### ISSUE TITLE
[BUG] %player% token no longer being resolved

### ISSUE THREAD

**Issue by noobanidus** [ErdbeerbaerLP/Discord-Chat-Integration#28]
**What happened?**
-Since updating to DCIntegration 1.1.8-1.14, messages relayed from Discord to Minecraft now appear as "%player% <the rest of the message here>" rather than the usual player name. 

**What should happen?**
-Presumably the token should be replace with the player's name.

**Steps to reproduce**
- Unable to give indication of reproduction steps.

**Version**
-
- [ ] 1.12
- [x] 1.14

Mod version 1.1.8

**Crash report if available (use https://paste.dimdev.org)**
-

**Additional info**
-

**Comment by Tander** [comment]
Same problem
![изображение](https://user-images.githubusercontent.com/1059805/70909885-86734e00-201f-11ea-9330-604b65962990.png)

**Comment by ErdbeerbaerLP** [comment]
Use %user% here.
https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/issues/25

**Comment by noobanidus** [comment]
Thanks for the clarification!

The default config still uses %player% which is why I wasn't sure, as I deleted the config to force it to regenerate a new one and then copied my Discord information back over.

**Comment by Tander** [comment]
For some reason mod uses msgChatMessage (which is currently = "**<%player%>** %msg%") instead of ingameDiscordMsg.

**Comment by ErdbeerbaerLP** [comment]
oh, that could have happened. Let me look at it

**Comment by ErdbeerbaerLP** [comment]
Yes, update gets pushed to curseforge (might take some time)
