### ISSUE TITLE
[BUG] msgChatMessage is the same for Ingame to Discord, and Discord to Ingame.

### ISSUE THREAD

**Issue by Gbergz** [ErdbeerbaerLP/Discord-Chat-Integration#29]
**What happened?**
- User talk ingame & discord talk share the same config line.

**What should happen?**
- They should be separate.

**Version**
-
- [ ] 1.12
- [X ] 1.14

Mod version: 1.1.8-1.14

**Information:**
Right now when i have %user% for "msgChatMessage =" it shows up normally from Discord Chat to MC, like this: ["[GYAZO]"](https://i.gyazo.com/7e14292c780c5bd90f8abfd639b9672f.png)| But if I have %user% it won't work from MC to Discord. Then it'll show up like this: "[[GYAZO]]"(https://i.gyazo.com/33e1eae7475e8a4e9250853dcef71d30.png) And if i swap them around its the same thing. Only one way works. Sorry if i explained this poorly.

**Comment by ErdbeerbaerLP** [comment]
Just fixed in #28

**Comment by ErdbeerbaerLP** [comment]
**Don't know if that link works** but you can try downloading it from this link: https://www.curseforge.com/minecraft/mc-mods/dcintegration/download/2844428
