### ISSUE TITLE
Is there a way to enter custom commands?

### ISSUE THREAD

**Issue by Mx772** [ErdbeerbaerLP/Discord-Chat-Integration#3]
Moved from the previous unsupported [discord integration ](https://www.curseforge.com/minecraft/mc-mods/discordintegration) to this one, and one of the big features I liked was the commands functionality - where you could enter your own commands to be ran. Is this possible already within the cfg?

**Comment by ErdbeerbaerLP** [comment]
I already planned to implement this, currently it only has the commands I provided.

**Comment by Mx772** [comment]
Well that was fast - Thanks for the quick response!

**Comment by ErdbeerbaerLP** [comment]
(you had luck for a quick response, currently have slow internet)

**Comment by Mx772** [comment]
Well that was fast. Thanks mate, I appreciate it. Trying to do some dumb stuff with a discord bot that would run a command and grab specific command output to then run other logic, as well as vote reboots, and a few other qol things. 

While I would normally use an API I figured since my implementation is already janky, might as well keep it as such. 

Thanks again
