### ISSUE TITLE
[BUG] Channel description updates break Discord on Android

### ISSUE THREAD

**Issue by gdude2002** [ErdbeerbaerLP/Discord-Chat-Integration#31]
I didn't fill out the form because it's pretty clear what's going on here: on the latest _stable_ version for Minecraft 1.12.2 (so, version 1.1.5), the bot doesn't check that the channel description actually needs to be edited - it just tries to edit it immediately.

This causes issues with Discord on Android at the moment - if you're trying to edit a message, the cursor will jump back to the end of the message every time the channel description is updated, whether the actual text has changed or not.

The solution is to check the channel description before attempting to edit it - and don't try to edit it if it wouldn't have changed.

---

This is technically a Discord bug, but it's impossible to submit bug reports at the moment - they've decided to lock all of the bug reporting channels until the 5th of January or so. Still, this should be an easy fix for you!

**Comment by gdude2002** [comment]
That was quick! Looking forward to a release ❤️

**Comment by ErdbeerbaerLP** [comment]
Curseforge rarely approves releases on weekends. I can give you the 1.12 version [here](http://api.erdbeerbaer.tk/dcintegration-1.1.10-1.12.jar)
![image](https://user-images.githubusercontent.com/27149563/71314282-94710680-2445-11ea-992c-8b29f231ff1e.png)

**Comment by gdude2002** [comment]
Thanks, I appreciate it

**Comment by gdude2002** [comment]
Unfortunately, the version you linked above didn't solve the problem. That said, I can't do any further testing tonight, so don't worry about rushing for a solution.

Thanks for you efforts so far, though.

If I get time tomorrow, I'll see if I can fix it myself.

**Comment by ErdbeerbaerLP** [comment]
If you remove the uptime it should update not that often (since the uptime updates every second)

**Comment by gdude2002** [comment]
Oh god, I didn't even think of that, haha.

You're right, it totally works. Thanks!
