### ISSUE TITLE
[BUG] Constant spam in logs:

### ISSUE THREAD

**Issue by Sakata-MC** [ErdbeerbaerLP/Discord-Chat-Integration#32]
**What happened?**
Constant spam in logs:
OkHttp https://discordapp.com/.../INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [OkHttp https://discordapp.com/...] WARN RateLimiter - Encountered 429 on route /channels/########

**What should happen?**
Not having the logs spammed to death

**Steps to reproduce**
- Server was up for... ~27 hours.

**Version**
-
- [X ] 1.12
- [ ] 1.14

Mod version 
dcintegration-1.1.5-1.12

**Additional info**
-
The logfile was bigger than the world save after only about a day.  Not lookin' good.

**Comment by ErdbeerbaerLP** [comment]
🤔 Too many requests... Does this happen more often? If yes try disabling the channel description changes.

**Comment by Sakata-MC** [comment]
still happens after reboot.  I've changed
```
S:CHANNEL_DESCRIPTION=%motd% (%online%/%max%) | %tps% TPS | Uptime: %uptime%
```
to
```
S:CHANNEL_DESCRIPTION=
```
and restarted today... hopefully that will change things, but ofc its reducing the usefulness of the bot.
The solution would be to rate limit the bot in the plugin.  Perhaps make it configurable.
