### ISSUE TITLE
[BUG] (1.14.4) Server Crashed.

### ISSUE THREAD

**Issue by Gbergz** [ErdbeerbaerLP/Discord-Chat-Integration#34]
**What happened?**
- Modpack Limitless Server for some reason crashed, randomly.

**What should happen?**
- No crash I suppose.

**Steps to reproduce**
1. Start server.
2. Have it open for awhile
3. Crash.

**Versions**
- Mod Version: **1.1.5**
- MC: **1.14.4**
- Forge: **28.1.107**

**Server Crash report**
- https://gist.github.com/Gbergz/3186fa85994ea40e71908b6491c37ae0

**Additional info**
- Actually no idea if this has to do with the mod or not. Reporting to just to be safe.

**Comment by ErdbeerbaerLP** [comment]
This is an lag problem. 
`ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)`

**Comment by Gbergz** [comment]
So it's a lag problem, no mods actual fault? Because i've been getting this alot and it's been calling out "false crashreports" on mods wildly.

**Comment by ErdbeerbaerLP** [comment]
Maybe it is an mod, maybe not. You can try deleting entities using this python script
https://github.com/Fenixin/Minecraft-Region-Fixer
(Don't know what parameters right now)

**Comment by Gbergz** [comment]
Just writing here now because got another "crash" [https://gist.github.com/Gbergz/3753c9c9d85f473cf06a96cd50440843](https://gist.github.com/Gbergz/3753c9c9d85f473cf06a96cd50440843)

probably not your mod but i really want to report it anyways. Have a look at it.

**Comment by ErdbeerbaerLP** [comment]
🤔 looks like this happened while stopping the server. I **think** it can simply be ignored because it simply attempted to get an value from the world while it was already unloaded
