### ISSUE TITLE
[Improvement] Ability to send different content to different channels

### ISSUE THREAD

**Issue by netish** [ErdbeerbaerLP/Discord-Chat-Integration#35]
I have a few suggestions related to the title:
1. I find the server activity messages and login messages would be better in another channel on my discord because they turn into spam.
2. The option to disable login messages as well as afk messages in the config (thanks for adding the latter).
3.  I'd like to be able to kick players using the Mee6 Bot that mutes/kicks users on discord - is that possible? I can see that you have admin commands in the cfg, but I am confused how to implement and there is no documentation how to do so. =(

Again thanks for this great mod and your hard work!

**Comment by ErdbeerbaerLP** [comment]
For 1 and 2:
I am working on implementing most of it. (Disabling AFK messages is already implemented)

For 3:
It is documented in the config *a little bit* and it also contains an example which already has an admin only kick command. If you need help creating the config, I can help you making it. Assuming you only want to kick, use 
`S:JSON_COMMANDS={"kick":{"adminOnly":true,"mcCommand":"kick","description":"Kicks a player from the server","useArgs":true,"argText":"\u003cplayer\u003e [reason]"}}` (formatted for 1.12 config)
Just set up the bot to use /kick <ingame name>

**Comment by netish** [comment]
Great I'm excited to hear that, and yeah I noticed the AFK part, I guess I wasn't clear I was thanking you for already implementing that!

I saw it but I was a bit confused and was hoping for in your wiki more documentation/explanation. I'll try your suggestion!
