### ISSUE TITLE
[BUG] Crash on playerLeave

### ISSUE THREAD

**Issue by Fenrirthviti** [ErdbeerbaerLP/Discord-Chat-Integration#36]
**What happened?**
Server crashes when a player leaves.

**What should happen?**
Server should not crash when a player leaves.

**Steps to reproduce**
Install mod, join server, leave server, observe crash.

**Version**
Minecraft: 1.15.1
Mod version 1.1.11
Forge version: 30.0.36

**Crash report if available (use https://paste.dimdev.org)**
https://gist.github.com/Fenrirthviti/d477ff1c338cae788663f967d01cb405

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
Fixed in new version (should be up soon on CurseForge)

**Comment by Fenrirthviti** [comment]
Thanks!
