### ISSUE TITLE
[Suggestion] Player Count/Server Status

### ISSUE THREAD

**Issue by Osprey4444** [ErdbeerbaerLP/Discord-Chat-Integration#37]
**What you want to be added?**

Integrate something like this into the bots, can be handy and looks pretty cool

https://www.reddit.com/r/discordapp/comments/8yn9hp/i_made_a_bot_that_shows_the_live_status_of_our/

Possibly make it a final feature for 1.12.2? (:

**Comment by ErdbeerbaerLP** [comment]
Feature added to 1.15 now
https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/raw/1.15/dcintegration-1.1.13-1.15.jar

In 1.12 I will maybe add it as an silent feature as soon as I find another bug to fix there
