### ISSUE TITLE
[BUG] Unable to get Admin Commands working

### ISSUE THREAD

**Issue by Darkere** [ErdbeerbaerLP/Discord-Chat-Integration#38]
I cannot get admin commands working. Everything else seems to be working just fine. 

**Steps to reproduce**
Set up Admin commands:
- roleID for admin
- add UUID to op.json

not 100% sure how to add the UUID as it is now a json and needs a name.

**Version**
Minecraft: 1.15.1
forge: 30.0.41
dcintegration-1.1.12-1.15

Config file (without bot token): https://pastebin.com/LkDYsf6w
latest.log: https://pastebin.com/M3tfCQn2
debug.log: https://pastebin.com/ECyy7iLk

**Comment by ErdbeerbaerLP** [comment]
What does it output when running such an command?

**Comment by Darkere** [comment]
Unknown Command. help command only shows the basic help, list, uptime commands.

**Comment by Darkere** [comment]
Downgrading to 1.1.0 fixes the issue.

**Comment by ErdbeerbaerLP** [comment]
Can you try if this version fixes it? I might have found the problem
https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/raw/1.15/dcintegration-1.1.13-1.15.jar

**Comment by Darkere** [comment]
Unfortunately, that did not fix the issue. 
Tried by changing out only the mod jar. 1.1.10 worked, 1.1.13 did not.

**Comment by ErdbeerbaerLP** [comment]
ok, i gonna add some more log output to the mod because this does not happen to me

**Comment by ErdbeerbaerLP** [comment]
Can you try again but then send me another log file? Should work using the same URL

**Comment by Darkere** [comment]
https://pastebin.com/vVALyy1E

**Comment by ErdbeerbaerLP** [comment]
Do you have the admin role or is the role ID invalid? It runs through all commands but does not think you are able to execute it

**Comment by Darkere** [comment]
Confirmed the admin role is correct by removing it and launching with 1.1.10. I no longer had access to the admin commands.


Another thing came to my attention though. Even without an admin role on 1.1.10 the tps command appears and is working. On 1.1.13 it does not appear under help and is not working.

**Comment by Darkere** [comment]
Problem is here:

https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/blob/0f08157a5f9917c339d585f93376771f16964f17/src/main/java/de/erdbeerbaerlp/dcintegration/commands/CommandFromCFG.java#L34

You are calling equals on a `String` and a `ConfigValue<String>`

**Comment by ErdbeerbaerLP** [comment]
Oh, thx for telling me. Weird is that it works fine for me tho
