### ISSUE TITLE
[BUG] Channel's topic doesn't update

### ISSUE THREAD

**Issue by hujle** [ErdbeerbaerLP/Discord-Chat-Integration#39]
**What happened?**
Channel's topic doesn't update after 2 hours server uptime.

**What should happen?**
It's should be work fine I guess.

**Steps to reproduce**
- Set botModifyDescription to true.
- Start the server.
- Wait for 2 hours ± 5 minutes.
- Get the error.

**Versions**
Minecraft version _1.15.2_
Forge version _31.1.0_
Mod version _1.1.13_

**Crash report if available**
- https://paste.dimdev.org/etegojiqaj.md

**Additional info**
- Nothing to say anymore.

**Comment by ErdbeerbaerLP** [comment]
Any other bot changing stuff on that channel?
The mod got rate limited on the channel :thinking:

**Comment by hujle** [comment]
I have Ayana and NotSoBot but the first one do nothing except (self)auto-role-stuff for members and the 2nd one is allowed to only one channel. Should the minecraft bot have the administrator permissions on the server?

**Comment by ErdbeerbaerLP** [comment]
No, that is not the problem.
It got rate limited from discord side. Did it send an large amount of messages recently? 


If you still want to test if it is because of permissions, invite the bot using this link: https://discordapi.com/permissions.html#536964176

**Comment by hujle** [comment]
It's already has all those perms. And yeah it also sends messages from mc chat to discord and vice versa and also has discord presence enabled. I noticed that the bot updates channel description too often and I think that's the reason why it's getting rate limited.

**Comment by ErdbeerbaerLP** [comment]
That should be fixed with #31 
Did you configure it to send seconds too? If yes remove the seconds

**Comment by hujle** [comment]
I didn't change anything in this so yes I have a seconds too.

**Comment by ErdbeerbaerLP** [comment]
Removing seconds might resolve this

**Comment by hujle** [comment]
By looking at audit log, seems like everything is fine and it doesn't update it that often. I dont have uptime in the description now but it doesn't really matter tbh.
