### ISSUE TITLE
[SUGGESTION] Add an option to turn off all messages from say commands run on the server

### ISSUE THREAD

**Issue by Sunconure11** [ErdbeerbaerLP/Discord-Chat-Integration#4]
Due to messages I have on my server meant for asking players to donate to keep it aloft, I would like an option to turn it off, so my discord is not flooded with messages for donations.

**Comment by ErdbeerbaerLP** [comment]
Will add that soon

**Comment by ErdbeerbaerLP** [comment]
You can early-download it here: http://erdbeerbaerapi.tk/dcintegration-1.0.9.jar
Just add `B:ENABLE_SAY_OUTPUT=false` to the messages config block or start and stop the server to let the mod add the entry, then set it to false
