### ISSUE TITLE
[Suggestion] Discord-based whitelist

### ISSUE THREAD

**Issue by vico93** [ErdbeerbaerLP/Discord-Chat-Integration#41]
I was on DigitalJesuit, a famous public server and noticed a interesting feature: the ability to "link/verify" Discord accounts (members of the server's guild) with Minecraft player names, and it allows a discord-based whitelist to be setup. If i'm not mistaken, only players with verified accounts on the Discord guild can join the server.

I think the plugin they are using is [this one](https://www.spigotmc.org/resources/discordsrv.18494/) or [this one](https://www.spigotmc.org/resources/discord-whitelister.69929/) for Spigot.

So, can this system be added to dcintegration as well? Thanks in advance!

**Comment by ErdbeerbaerLP** [comment]
~~Copy Paste~~
I already thought about implementing this

**Comment by ErdbeerbaerLP** [comment]
Forgot to close this, as it is implemented
