### ISSUE TITLE
[BUG] Crash on start with FTB Utilities (1.12)

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ErdbeerbaerLP/Discord-Chat-Integration#42]
**Hespin2K**

> I just noticed that if I remove DI everything works, if I remove FTB everything works too. But not together. The logs took off. It is at this point that the server loads endlessly
> 
>  https://paste.gg/p/anonymous/6640df1907704fa69b5eb1904d1b99e4

I am unable to reproduce this, can you send me the config file? Also which mod versions are you using (both ftb)?

**Comment by Hespin2k** [comment]
https://paste.gg/p/anonymous/adff60357d98430592d8566a194b0e26
Its configs
I use dcintegration-1.1.11-1.12 and FTBUtilities-5.4.0.124.jar

**Comment by ErdbeerbaerLP** [comment]
**You now should re-generate your bot token! If not someone else can run code on the bot!**

Any other mods installed? Since it still starts for me locally it might be an issue with yet another mod, even tho it starts without ftb

**Comment by Hespin2k** [comment]
This full mod list. And if I delete configs anyway server will be crash
appliedenergistics2-rv6-stable-7.jar
  | authmod-2.6.jar 
  | Chameleon-1.12-4.1.3.jar
  | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  
  | coroutil-1.12.1-1.2.36.jar
  | CraftTweaker2-1.12-4.1.20.jar
  | DynamicLights-1.12.2.ja
  | FTBLib-5.4.5.0.jar
  | FTBUtilities-5.4.0.124.jar
  | gregtech-1.12.2-1.9.0.481.jar
  | HardcoreDarkness-MC1.12.2-2.0.jar
  | jei_1.12.2-4.15.0.291.jar
  | NotEnoughItems-1.12.2-2.4.3.245-universal.jar
  | NuclearCraft-2.18o-1.12.2.jar
  | railcraft-12.0.0.jar
  | Shadows_of_Greg-1.12.2-2.13.0.jar
  | StorageDrawers-1.12.2-5.4.0.jar
  | TerraFirmaCraft-MC1.12.2-0.29.4.119.jar
  | zombieawareness-1.12.1-1.11.16.jar

**Comment by ErdbeerbaerLP** [comment]
Still starts without any problems for me 🤔 
Try re-downloading the current version, maybe your download got corrupted
