### ISSUE TITLE
[BUG] Colour Codes not being removed from Discord even after updating config.

### ISSUE THREAD

**Issue by Osprey4444** [ErdbeerbaerLP/Discord-Chat-Integration#44]
**What happened?**
- Colour Codes not being removed from Discord even after updating config.

**What should happen?**
- Colour Codes should be removed from Discord

**Steps to reproduce**
- Not too sure.

**Version**
- 1.12.2

Mod version - dcintegration-1.1.10-1.12

**Additional info**
Config - https://gist.github.com/Osprey4444/8dc1b9e7169aee0fdeb7168876b045ea
Discord Screenshot - https://i.imgur.com/pYWCXdv.png

**Comment by ErdbeerbaerLP** [comment]
Seems to be another mod adding & instead of § as color code symbol

**Comment by Osprey4444** [comment]
It can't be, I tested it on a Server with 0 serverside mods other than DCIntegration.

**Comment by ErdbeerbaerLP** [comment]
To test, can you enable the webhook mode?
(also **regenerate your bot token**)
