### ISSUE TITLE
Logger Error [BUG] 

### ISSUE THREAD

**Issue by LightningManGTS** [ErdbeerbaerLP/Discord-Chat-Integration#45]
**What happened?**
- mod failed to load

**Steps to reproduce**
- install mod
- start server
-?

**Version**
-
- [x] 1.12

Mod version _1.1.13_

newest to oldest

16.03 16:11:19 [Server] JDA MainWS-WriteThread/INFO [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-WriteThread] INFO WebSocketClient - Connected to WebSocket
16.03 16:11:17 [Server] JDA MainWS-WriteThread/INFO [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-WriteThread] WARN WebSocketClient - Got disconnected from WebSocket. Appending to reconnect queue
16.03 16:11:17 [Server] JDA MainWS-WriteThread/INFO [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-WriteThread] ERROR WebSocketClient - Encountered IDENTIFY Rate Limit! Waiting 54 milliseconds before trying again!
16.03 16:11:12 [Server] JDA MainWS-ReadThread/INFO [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
16.03 16:11:11 [Server] Server thread/INFO [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [Server thread] INFO JDA - Login Successful!
16.03 16:10:58 [Server] Server thread/INFO [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
16.03 16:10:58 [Server] Server thread/INFO [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation MDCAdapter implementation.
16.03 16:10:58 [Server] Server thread/INFO [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
16.03 16:10:54 [Server] Server thread/INFO [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
16.03 16:10:54 [Server] Server thread/INFO [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: Defaulting to no-operation (NOP) logger implementation
16.03 16:10:54 [Server] Server thread/INFO [STDERR]: [dcshadow.slf4j.helpers.Util:report:128]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
16.03 16:10:54 [Server] Server thread/INFO [STDOUT]: [de.erdbeerbaerlp.dcintegration.DiscordIntegration:preInit:409]: Loading mod

**Comment by LightningManGTS** [comment]
I say that as it skipped eventually after not skipping for five minutes? discord related issues?

https://pastebin.com/Dskff9DU

**Comment by ErdbeerbaerLP** [comment]
Yes, discord hat problems
https://status.discordapp.com/incidents/62gt9cgjwdgf
