### ISSUE TITLE
[BUG] 1.15.2- seems to be incompatible with newer forge builds past build 24

### ISSUE THREAD

**Issue by SDUBZ** [ErdbeerbaerLP/Discord-Chat-Integration#47]
**What happened?**
-joins server with forge 31.1.27
get spammed on console and gets kicked a few seconds later

**What should happen?**
- join server and everything run as it did in earlier builds of forge

**Steps to reproduce**
- join server with forge mentioned above and mod version mentioned below

**Version**
1.15.2

Mod version _0.0.0_
dcintegration-1.1.14-1.15.jar

Logs:
https://gist.githubusercontent.com/SDUBZ/749e37fc70f1e27478385f877dc6f4c0/raw/baec126efbcc2200074ad5d92982cf13553512d5/latest.log

https://gist.githubusercontent.com/SDUBZ/249b07300aff638ba3b2d6026ac46d9b/raw/89b31ad81c81f9a978e124418107bf5e9025d68a/debug.log

**Comment by ErdbeerbaerLP** [comment]
Can you try if it works with this version? It should.

(Note that this is an alpha with features which might be broken. If you don't want to use the new feature set allow-linking to false in the config.)

**Comment by SDUBZ** [comment]
nope still breaks after a few mins and spamms console and kicks players
[latest.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4398528/latest.log)



[debug.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4398527/debug.log)

**Comment by ErdbeerbaerLP** [comment]
Does it (the timeout kicks) still happen without this mod? The log spam was usually only used in development but I forgot to remove the message

**Comment by SDUBZ** [comment]
no it doesnt kick at all without the mod thats why i reported once i found it out so you could get it fixed

**Comment by SDUBZ** [comment]
This also doesnt happen on a virtual server you setup on your pc but only  a true dedicated server that is remote

**Comment by ErdbeerbaerLP** [comment]
Does this happen without an mixin loader/bootstrap mod? Maybe the mod replaces something so it breaks

**Comment by SDUBZ** [comment]
im not sure to that extent cant really do alot of testing when you have players on your server wanting to build etc
but could be conflicting with other server side mods too like ma essentials

**Comment by ErdbeerbaerLP** [comment]
Just installed ma essentials and it does not seem to cause this bug. Something seems to get the client to disconnect for some reason. Did it send any messages to discord? Maybe that is an problem

**Comment by SDUBZ** [comment]
well i was testing to see if it was sending to discord
and not long after the spam did happen on console

**Comment by Alkiasan** [comment]
Having the same issue here. 
![image](https://user-images.githubusercontent.com/62717881/78603555-3e876980-7850-11ea-9137-1796f98ffd94.png)
Here's the error if it helps.
Running 1.14.4 on a server using forge 28.2.0
