### ISSUE TITLE
[Request]: 1.19 specific version support

### ISSUE THREAD

**Issue by mimi-min** [ErdbeerbaerLP/Discord-Chat-Integration#479]
### Explain your idea

I'm running a server on 1.19, and unfortunately it crashes when a mod is listed as 1.19.1....

Is it possible to release a 1.19 specific version?

### If this is platform-dependant, which platform is this about?

Forge

**Comment by SmallPepperZ** [comment]
You can find the older version of the mod for 1.19 [on Modrinth](https://modrinth.com/mod/dcintegration/version/2.4.5-1.19). If you want the newer features or bug fixes, you will need to update to 1.19.2 (or 1.19.1)

**Comment by mimi-min** [comment]
Got it, thank you!!
