### ISSUE TITLE
[Suggestion] /console exec command in Discord

### ISSUE THREAD

**Issue by ReinitiaIized** [ErdbeerbaerLP/Discord-Chat-Integration#48]
**What you want to be added?**
I'd like to allow those who have the ADMIN_ROLE to be able to directly execute on the Server console. This is so I can easily give people remote access to the console for supporting my community where needed.

I know the CurseForge said 1.12.x would no longer receive feature updates, but it would be really appreciated if you could push this to it.

**Comment by ErdbeerbaerLP** [comment]
You can add an custom admin only command with mc command "" that would execute everything it gets as server command.

Here is an pre-made config entry for commandJson
```json
{"exec":{"adminOnly":true,"mcCommand":"","description":"Executes an command","useArgs":true,"argText":"<command>"}}
```
that adds an exec command available to all users with the configurated admin role to discord executing all commands it gets (`/exec say hi` -> should execute `say hi` as command)
