### ISSUE TITLE
[BUG 1.15.2] Console spam

### ISSUE THREAD

**Issue by ocram9** [ErdbeerbaerLP/Discord-Chat-Integration#49]
**What happened?**
When the server has been running for a while the mod starts spamming the console with this message: 
[31mrt2020 21:39:08.418] [OkHttp https://discordapp.com/.../INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [OkHttp https://discordapp.com/...] WARN RateLimiter - Encountered 429 on route /channels/688576384859504655

I'm not sure it that is this is a problem with the mod or with discord but I thought I would post it here anyway.
**What should happen?**
Not spamming the console

**Steps to reproduce**
- Run the server
- Error appears

**Version**
- 1.15.2
- DiscordIntegration-1.1.14 (MC 1.15)
- Forge 31.1.30

**Config file**
- https://gist.github.com/ocram9/e921374c18badd9bcd779d08e2ed10af

**Comment by ErdbeerbaerLP** [comment]
Lower the accuracy of the uptime in channel topic (I really need to change the default config value..)
See #39
