### ISSUE TITLE
[BUG] 1.14.4 No chat being sent to Discord.

### ISSUE THREAD

**Issue by Osprey4444** [ErdbeerbaerLP/Discord-Chat-Integration#50]
**What happened?**
- No chat being sent from the game to Discord and no chat being sent from Discord to the game.

**What should happen?**
- Chat should be sent to both parties

**Steps to reproduce**
- Not too sure. 

**Version**
- 1.14

Mod version _1.1.14_

**Config file**
- https://hastebin.com/epimufikos.bash

**Crash report if available (use https://paste.dimdev.org)**
- No crash report.

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment]
Can you try without `chatInputID` and `chatOutputID`?
