### ISSUE TITLE
[Bug]: Default webhook name should not have DISCORD in it

### ISSUE THREAD

**Issue by Ricket** [ErdbeerbaerLP/Discord-Chat-Integration#500]
### What happened?

Bot failing to send to discord, hit the error in #488 

I figured out it's because the `webhookName` config has "DISCORD" in the name. Once I changed it to the value `"MC_E6E_DCINTEGRATION"` then it succeeded.

Default webhookName should not have "discord" in the name, apparently discord api disallows it.

### Game Version

1.16

### What platform are you using?

Forge

### Platform version

14.23.5.2860

### Config File

see #488

```
webhookName = "MC_DISCORD_INTEGRATION"
```

### Crash report / Error log (if applicable)

see #488

**Comment by ErdbeerbaerLP** [comment]
Known and fixed in 2.5.0 (when doing next update, I will also push a update to 1.16 again for a last time)
