### ISSUE TITLE
[BUG] Unknown command at position 0

### ISSUE THREAD

**Issue by sigsus** [ErdbeerbaerLP/Discord-Chat-Integration#51]
**What happened?**
- when i try to do a command from discord that isnt /help, i get "Unknown command at position 0: <--[HERE]"

**What should happen?**
- the command being executed

**Steps to reproduce**
-  *shrug*

**Version**
- 1.15.2

Mod version 1.1.14

**Config file**
- [dcintegration-common.toml.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4445849/dcintegration-common.toml.txt)

**Crash report if available (use https://paste.dimdev.org)**
- no crashes

**Additional info**

- ![image](https://user-images.githubusercontent.com/6548465/78694635-3fc2a000-78fd-11ea-8c2e-e1b26df2c1c2.png)

**Comment by ErdbeerbaerLP** [comment]
It is the same message vanilla would return. You need to provide an argument or more
(/kick <player>)

**Comment by ErdbeerbaerLP** [comment]
Oh, /stop also does this... That is not normal, reopening

**Comment by sigsus** [comment]
![PartialScreenshot_20200408-100516](https://user-images.githubusercontent.com/6548465/78759950-b2c12a80-7980-11ea-8b12-0b114437ece0.png)
Here's with name

**Comment by ErdbeerbaerLP** [comment]
I can't reproduce this for some reason 🤔 
![image](https://user-images.githubusercontent.com/27149563/78760683-ce790080-7981-11ea-89ec-7ef18350e91e.png)
(the message is normal when no argument was specified, it is the same vanilla would output)

**Comment by sigsus** [comment]
Can it be because i have server utilities mod?

**Comment by ErdbeerbaerLP** [comment]
Let me test if it happens with it

**Comment by ErdbeerbaerLP** [comment]
Yes, it is caused by this mod

**Comment by ErdbeerbaerLP** [comment]
I found the problem. The fake player i am using to run commands does not have * permissions. I will add code to create the file on launch. Place this in your world/playerdata folder:
[8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3.pdat.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4449341/8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3.pdat.txt)
**(remove the .txt from the file)**
