### ISSUE TITLE
[BUG] DiscordIntegration-1.2.1 (MC 1.15) Custom commands not showing output in discord.

### ISSUE THREAD

**Issue by STOKE-STER** [ErdbeerbaerLP/Discord-Chat-Integration#54]
**What happened?**
- Ran a custom command in discord (/entitycount runs the "/forge entity list" command in game), command executes successfully the first time after a reboot. All subsequent times after that for this command or any other custom commands run successfully in game but don't show an output in discord.

**What should happen?**
- Commands should run in game, and display the output in discord.

**Steps to reproduce**
- Make a custom command, can be anything like "/ping playername". Command will run successfully the first time after a fresh server restart, all subsequent times after that the command wont show in discord.

**Version**
- 1.15.2

Mod version _1.2.1_

**Config file**
-https://pastebin.com/u1QjKEPF

**Additional info**
Default commands like /list seem to work but not custom commands. It's also worth noting this issue has been around in the last few versions for 1.15.
Screenshot of problem
![dcint](https://user-images.githubusercontent.com/36657224/78958256-e93aa900-7b2a-11ea-9e7c-ef9e700f619e.PNG)

**Comment by ReinitiaIized** [comment]
I second this not occurring. Weirdly enough, if I do a raw exec command (directly execute into console), when I use the tp command, it'll show the output for that (meaning it picks up on messages sent to the "operator"). However, information from the console is not returned

**Comment by ReinitiaIized** [comment]
I believe this to be the relevant error, as a fresh Server will print the console out the first time, however any attempts afterwards results in no response from the mod
```
Exception in thread "Thread-8" [16:15:15] [Thread-8/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ConcurrentModificationException
[16:15:15] [Thread-8/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.util.HashMap.forEach(HashMap.java:1292)
[16:15:15] [Thread-8/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at de.erdbeerbaerlp.dcintegration.Discord.lambda$new$1(Discord.java:224)
[16:15:15] [Thread-8/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by ErdbeerbaerLP** [comment]
Ah I see why
Looks like I accidentally moved an code line. Going to fix that

**Comment by STOKE-STER** [comment]
I saw this got a fix for mc1.12, any chance you could fix the mc1.15 version?

**Comment by ErdbeerbaerLP** [comment]
In 1.15 you need to download the alpha 1.2.2
