### ISSUE TITLE
[Suggestion] Discord text formatting to differentiate player chat from bot messages

### ISSUE THREAD

**Issue by dirtbirb** [ErdbeerbaerLP/Discord-Chat-Integration#55]
I'd like to declutter the Discord output a bit. I don't know the best way to do that, but as a naive suggestion I'd say maybe **bold** for player names when chat is sent from in-game, and `code` for messages sent from the bot itself.

I will attach a very simple merge request that I hope achieves this, but I don't actually know what I'm doing, and any feedback is appreciated.

**Comment by ErdbeerbaerLP** [comment]
The messages are configurable using the config file
You can change that how you like.
Just seen the PR, you attempted to hard-code that, so no one could change/remove the code blocks.
Rather use the config

**Comment by dirtbirb** [comment]
Oh awesome, thank you! Wasn't aware of that option.
