### ISSUE TITLE
[BUG] Server keeps crashing after it was moved to a different node

### ISSUE THREAD

**Issue by Decaf1** [ErdbeerbaerLP/Discord-Chat-Integration#57]
**What happened?**
- Server was moved to a different node, crashed every startup

**What should happen?**
-

**Steps to reproduce**
- Put the 1.1.14 jar in mods folder
- Start server and keeps crasing

**Version**
-
- [x] 1.12
- [ ] 1.14

Mod version _1.1.14_

**Config file**
https://pastebin.com/sE3VzNhy

**Crash report if available (use https://paste.dimdev.org)**
`Caused by: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated`

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment]
Try adding _aaa to the start of the file name to let it load before all other mods. Might be some other mod loading before and using an older version of Mixin

**Comment by Decaf1** [comment]
I have tryed your solution, does not work.
Keeps crashing after my host switched machines for me. Before worked like a charm.

https://pastebin.com/iNfCPJAz
^Server Log.

When removing your plugin .jar no problems when adding it instant crash even when naming it _aaa to top. still crash

Regards,
J

**Comment by Decaf1** [comment]
Does the mod use a specific port?

**Comment by ErdbeerbaerLP** [comment]
It doesn't use any. It communicates with https://discordapp.com/api

**Comment by ErdbeerbaerLP** [comment]
Does it work with version 1.1.13? It uses an older version of mixin, so it might be more compatible with other mods

**Comment by Decaf1** [comment]
> Does it work with version 1.1.13? It uses an older version of mixin, so it might be more compatible with other mods

We use minecraft 1.12.2 with Revelation 3.2.0 Mod Pack

**Comment by ErdbeerbaerLP** [comment]
Try with mod version 1.1.13 on your server instead of the latest one (1.1.14)
