### ISSUE TITLE
[Suggestion]: Compatibility with vanish on fabric

### ISSUE THREAD

**Issue by EngineerPanda** [ErdbeerbaerLP/Discord-Chat-Integration#591]
### Explain your idea

I would like my vanish mod to actually work, lol
[https://modrinth.com/mod/vanish](https://modrinth.com/mod/vanish)

### If this is platform-dependant, which platform is this about?

Fabric

**Comment by EngineerPanda** [comment]
wrong page, it was supposed to be on fabric

**Comment by EngineerPanda** [comment]
there doesnt seem to be an issues page for fabric, so im opening it again

**Comment by benshan36** [comment]
Vanish support has been added with version 3.1.0
@ErdbeerbaerLP Recommend closing issue
