### ISSUE TITLE
Add IMC for mod compatibility

### ISSUE THREAD

**Issue by 4rz0** [ErdbeerbaerLP/Discord-Chat-Integration#6]
I recommend adding a way for other mods to send messages to discord, for example Forge's IMC feature.
That way, other mods like BetterQuesting could send their own achievements to Discord, or server management mods could send notifications.

**Comment by ErdbeerbaerLP** [comment]
I will look at it later. Currently other mods can call sendMessage on the discord isntance

**Comment by ErdbeerbaerLP** [comment]
Wait for the file to be approved. I attempted to add compatibility for my custom one (key: `Discord-Message`) and the one from the other Discord Integration mod by Chikachi
