### ISSUE TITLE
[Suggestion] Emojicord integration

### ISSUE THREAD

**Issue by TheSpicePhantom** [ErdbeerbaerLP/Discord-Chat-Integration#61]
**What you want to be added?**
At this very moment, Discord-Chat-Integration, does not seem to be capable of displaying emojis in minecraft chat. (Looks like this: [][])
Now, there is a mod that adds discords emojis to minecraft, called "Emojicraft".
[Emojicraft - on Curseforge](https://www.curseforge.com/minecraft/mc-mods/emojicord)
[TeamFruit Github](https://github.com/Team-Fruit/Emojicord)

Maybe have DCI utilise Emojicraft, if it's installed?

Version: 1.14.4+

Thank you :)

**Comment by ErdbeerbaerLP** [comment]
Mod now has an better implementation. (1.15 only)
Note that you have to import the emotes from that server AND the server requires to have emojicord installed for this to work too

(Forgot to close this in 47bc8a6a26a0efdd291e9525204f8905daa996b1)
