### ISSUE TITLE
[BUG] /discord doesn't send an invite link, it toggles ignoring discord instead

### ISSUE THREAD

**Issue by STOKE-STER** [ErdbeerbaerLP/Discord-Chat-Integration#66]
**What happened?**
/discord toggles ignore discord messages

**What should happen?**
/discord should send the player an invite link

**Steps to reproduce**
type /discord in game

**Versions**
MC 1.15.2
dcintergration-1.2.2-1.15
forge 31.1.77

**Config file**
-

[dcintegration-common.zip](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4607796/dcintegration-common.zip)
 (Had to zip it bc git doesn't support .toml files)

**Comment by ErdbeerbaerLP** [comment]
Forgot to close,
Fixed in commit 54775b2736394be6e314c2459efd92a1b2fe5c94
