### ISSUE TITLE
[BUG] Occassional STDERR Console Spam

### ISSUE THREAD

**Issue by SSyl** [ErdbeerbaerLP/Discord-Chat-Integration#67]
**What happened?**
- Once every hour or so I'll get the following error messages in my server console:
`[01:46:44] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-ReadThread] WARN WebSocketClient - Got disconnected from WebSocket. Attempting to resume session`
`[01:46:46] [JDA MainWS-ReadThread/INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [JDA MainWS-ReadThread] INFO JDA - Successfully resumed Session!`

**What should happen?**
- Seeing as it's only a disconnect for a second or two, I'd rather it only notify me if it got disconnected and was not able to reconnect for at least a minute. Maybe make the time configurable?

**Steps to reproduce**
- Boot up a server
- Let it run for an hour or two
- Error message about getting disconnected from WebSocket will appear and then a few seconds later it will say it successfully resumed session. (if you leave it running overnight you'll see the error messages 5-8 times)

**Version**
Minecraft 1.12.2
Forge 14.23.5.2847

DiscordIntegration-1.1.15 (MC 1.12)

**Config file**
[Discord-Integration.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4608084/Discord-Integration.txt)

**Comment by ErdbeerbaerLP** [comment]
There is no way for disabling that log as JDA has that hardcoded without any option to disable it.

This is where the log comes from:
https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java#L473
