### ISSUE TITLE
[BUG] Server crashing / Rate Limit spam

### ISSUE THREAD

**Issue by SilverKytten** [ErdbeerbaerLP/Discord-Chat-Integration#70]
**What happened?**
- The server randomly crashed with the error 
"[04:50:00] [OkHttp https://discordapp.com/.../INFO] [STDERR/]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [OkHttp https://discordapp.com/...] WARN RateLimiter - Encountered 429 on route /channels/666310434931998750"
and will not start back up, regardless of whether I have the DCintegration mod in or not.
**What should happen?**
- It should not

**Steps to reproduce**
- No idea. It just happened after about 2 days of solid uptime. I can't get the server to start back up, at all. 
[latest.log](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4699747/latest.log)

- 

**Version**
- 1.1.14 1.15.2

**Config file**
-
[dcintegration-common.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4699753/dcintegration-common.txt)

*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
-
[dcintegration-common.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4699754/dcintegration-common.txt)

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment]
For the rate limits change this config value:
uptimeFormat = "dd 'days' HH 'hours' mm 'minutes'
(just remove the seconds)

However the crash without the mod can't be from this mod, since it is not loaded

**Comment by SilverKytten** [comment]
Alright, well that stopped the crashing but it's still spamming the console with the same error. 
![image](https://user-images.githubusercontent.com/2188185/83283788-5bca1b80-a1a1-11ea-8d6f-c05ced1ba038.png)

**Comment by ErdbeerbaerLP** [comment]
Seems to be an discord issue. Had the same problem today while testing, maybe it is gone tomorrow

**Comment by SilverKytten** [comment]
ok, thank you

**Comment by michaeljory** [comment]
I'm getting the same spam in my server logs.  Is discord.com rate limiting this mod now?

**Comment by SilverKytten** [comment]
So, I changed the %uptime% placeholder out, and it got rid of the spam for now. 
![image](https://user-images.githubusercontent.com/2188185/83313761-28a57d80-a1dd-11ea-9e6e-49ef386927a4.png)

It's at least a temporary fix.

**Comment by SilverKytten** [comment]
(I just changed %uptime% to uptime as a test because the spam prevents the server from starting for some reason)

**Comment by ErdbeerbaerLP** [comment]
Discord changed something and I need to update the library I use. Update will come out soon

**Comment by ErdbeerbaerLP** [comment]
Hotfix: set botModifyDescription to false

**Comment by RomualdYT** [comment]
Any news about it ? :)

**Comment by ErdbeerbaerLP** [comment]
Upvote theese so discord will maybe revert thier change
[https://support.discord.com/hc/en-us/community/posts/360067755532-Increase-rate-limit-for-editing-channel-description](https://support.discord.com/hc/en-us/community/posts/360067755532-Increase-rate-limit-for-editing-channel-description)
[https://support.discord.com/hc/en-us/community/posts/360067891912-Channel-Topic](https://support.discord.com/hc/en-us/community/posts/360067891912-Channel-Topic)
