### ISSUE TITLE
[BUG] Console spam

### ISSUE THREAD

**Issue by Haibane-Kira** [ErdbeerbaerLP/Discord-Chat-Integration#71]
**What happened?**

Console spam with this
`[14:38:45] [OkHttp https://discordapp.com/.../INFO] [STDERR]: [net.dv8tion.jda.internal.utils.SimpleLogger:write:277]: [OkHttp https://discordapp.com/...] WARN RateLimiter - Encountered 429 on route /channels/553962443169333249`
553962443169333249 is channel ID from DCI should get messages to the server.
previously everything worked fine, but for now it's always about this spam messages, about 4 messages at a time, then several seconds of cooldown and repeat.
Changing "DESCRIPTION_UPDATE_DELAY" in config changes nothing
Also DCI works fine even with this errors, but  creating additional delay at least while server start.
All message transfer from and to channels still works, but log is now trash even if no one on server or talking in Discord chat.

**Steps to reproduce**
- Not sure for someone else, but by the log you can see it comes just with started server

**Version**

- MC 1.12.2
- DCI 1.1.16

**Config file and log file**

https://gist.github.com/Haibane-Kira/448753f46e5a58fb6955d5e044591951

**Additional info**

this happenned on 1.1.14, then i updated DCI to 1.1.16, but no changes.

**Comment by roflobster** [comment]
Want to add I am getting the same error.  I tried both the DCI 1.1.16 and the older 1.1.10, same results.    Other Discord mods do not do this and I understand this is an older version, but I love yours it has all the features I want so hoping something can be done for this.

Will add I am running the FTB Ultimate Reloaded (1.12.2) if it matters.

**Comment by ErdbeerbaerLP** [comment]
Remove the seconds from the uptime format

**Comment by ErdbeerbaerLP** [comment]
Discord changed something and I need to update the library I use. Update will come out soon

**Comment by DeathSmurf** [comment]
Okay, i thought i was the only one with this problem ... suddenly jumped from a day or two ago.
**Thanks for your great work with this mod.** I will look forward to the next update.

**Comment by Haibane-Kira** [comment]
one more problem with it:
if server is restarted by /stop command, it can't stop completly since mod trying to do something again and again with same errors.

**Comment by ErdbeerbaerLP** [comment]
Disable channel description updates for now
