### ISSUE TITLE
1.12.2 Server Crash Null Pointer[BUG] 

### ISSUE THREAD

**Issue by aetherpirate** [ErdbeerbaerLP/Discord-Chat-Integration#73]
Server Crash on startup

- 

**Version**
1.12.2, forge 2847

dcintegration-1.1.17-1.12.jar

using default config
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

[crash-2020-06-01_10.50.44-server.txt](https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/files/4712005/crash-2020-06-01_10.50.44-server.txt)
-

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment]
It should not actually crash but you did not configurate it.
Here is how to set up: https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/wiki/Quick-Setup
