### ISSUE TITLE
[BUG] Server will not start with mod installed

### ISSUE THREAD

**Issue by coffeeordeath** [ErdbeerbaerLP/Discord-Chat-Integration#75]
**What happened?**
- tried to load up Manufactio server with this mod but it will not start at all. 

**What should happen?**
- server should start and discord integration should work

**Steps to reproduce**
- simply place discord integration in mods folder
- 

**Version**
-
- [ x ] 1.12
- [ ] 1.14

Mod version dcintegration-1.1.17-1.12

**Config file**
- https://pastebin.com/xGq6EgjJ
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
- paste.dimdev gives a 502 error i used pastebin instead
https://pastebin.com/ympgwkpW

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment]
can you try with mod version 1.1.13?
https://www.curseforge.com/minecraft/mc-mods/dcintegration/files/2895554

**Comment by coffeeordeath** [comment]
server will start with that version. thank you!
