### ISSUE TITLE
[BUG] Crash using 1.2.9 build for 1.15

### ISSUE THREAD

**Issue by vico93** [ErdbeerbaerLP/Discord-Chat-Integration#77]
**What happened?**
- I got [this crash report](https://hastebin.com/toveriteqa.sql) when trying to boot Minecraft (singleplayer) after updating Discord Integration.

**What should happen?**
- The game should load

**Steps to reproduce**
- Update dcintegration on 1.15 from 1.2.6 to 1.2.9
- Open the game

**Version**
- [ ] 1.12
- [ ] 1.14
- [x] 1.15

Mod version _1.2.9_

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
- [The default](https://hastebin.com/carepozaju.bash), since i didnt use it on singleplayer (only is on my profile folder because i sync the modpack between clients and server using git)

**Additional info**

- Nothing i can remember

**Comment by ErdbeerbaerLP** [comment]
The crash is an known issue (emojicord stuff) and I am working on a fix

But the mod does nothing on singleplayer

**Comment by vico93** [comment]
> The crash is an known issue (emojicord stuff) and I am working on a fix
> 
> But the mod does nothing on singleplayer

I know, but since Forge removed the `version` subfolder on `mods` (i was using it since 1.7 to keep "separated" universal mods from single or client-only mods, it needed to keep sit on mods regardless of side (i use git to keep my client and dedicated server synced).

**Comment by ErdbeerbaerLP** [comment]
ah,

just found a fix. Will be included in the next update (will be an larger one).
You can downgrade or install emojicord to fix the crash for now

**Comment by vico93** [comment]
> ah,
> 
> just found a fix. Will be included in the next update (will be an larger one).
> You can downgrade or install emojicord to fix the crash for now

Thanks! Will keep using previous version until the fix is published.
I just don't know if should i close the issue or wait the fix to close it.

**Comment by ErdbeerbaerLP** [comment]
I jsut close it with the commit when I release. Keeping this open likely prevents duplicate issues
