### ISSUE TITLE
[1.15.2] Player avatars not showing in Discord

### ISSUE THREAD

**Issue by mr-poyo** [ErdbeerbaerLP/Discord-Chat-Integration#78]
**What happened?**
- Player avatars (minecraft head) not showing in discord. Was a nice feature in earlier versions, I'm not sure if I screwed something up between updates.

**What should happen?**
- Discord used to show my minecraft avatar when talking from in-game.

**Steps to reproduce**
- install dcintegration-1.3.0-1.15.jar

**Version**
-
- [ ] 1.12
- [ ] 1.14
- [ x] 1.15

Mod version dcintegration-1.3.0-1.15.jar

**Config file**
- https://pastebin.com/VzZQuaLL
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
-

**Additional info**

- 
![image](https://user-images.githubusercontent.com/11811815/84403248-7213b500-ac40-11ea-8983-9b8b3c9c1f29.png)

**Comment by ErdbeerbaerLP** [comment]
Looks like I accidentally broke that while fixing the server avatar
