### ISSUE TITLE
Can't shutdown with Mohist on 1.12.2 [BUG] 

### ISSUE THREAD

**Issue by RomualdYT** [ErdbeerbaerLP/Discord-Chat-Integration#79]
**What happened?**
- Shutdown don't work

**What should happen?**
- Many errors
https://haste.chaun14.fr/yeyetizene.shell

**Steps to reproduce**
- Use Mohist
- 1.12.2 version your mod
- Start :)

Hope you can find a way to fix this :)

**Version**
-
- [ ] 1.12
- [ ] 1.14
- [ ] 1.15

Mod version _0.0.0_

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
-

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment]
Disable MODIFY_CHANNEL_DESCRIPTION and see if it works without it
