### ISSUE TITLE
Crash when server runs /stop

### ISSUE THREAD

**Issue by osmanosman88** [ErdbeerbaerLP/Discord-Chat-Integration#8]
Every time the server gets either manually stopped or scheduled restart runs through the server crashes. 
https://pastebin.com/RgWMgW6r

I thought that was the bot just saying oh it crashed but I noticed a bunch of the same crash reports.

**Comment by ErdbeerbaerLP** [comment]
Ignore that, i will try to fix that in the next update but it might still appear. It attempted to use the JDA instance but it was already killed

**Comment by osmanosman88** [comment]
BTW I forgot to mention I mean it crashes when the server itself runs /stop on console
