### ISSUE TITLE
[BUG] 1.3.1 for 1.15.2 - mod requires MixinBootstrap but server crashes with it

### ISSUE THREAD

**Issue by Partonetrain** [ErdbeerbaerLP/Discord-Chat-Integration#80]
**What happened?**
Server should start with MixinBootstrap

**What should happen?**
Crashes with "cannot hotload overworld"

**Steps to reproduce**
- Install just DCIntegration and MixinBootstrap
- Start server
- Crash

**Version**
- [x] 1.15 
Forge 31.2.9

Mod version _1.3.1_

**Config file**
Any, I think.

**Crash report if available (use https://paste.dimdev.org)**
https://pastebin.com/gs7TmMDC

**Comment by Partonetrain** [comment]
Happens with 1.1.14-1.15 as well...

**Comment by zoyer2** [comment]
yep happens for me too. it happens with all minecraft to discord mods on 1.15. Must be something to do with mixin
