### ISSUE TITLE
[Suggestion] Use environment variables for configuration

### ISSUE THREAD

**Issue by Malien** [ErdbeerbaerLP/Discord-Chat-Integration#81]
We are using git to version our modpack. Mainly for the convenience of git pull-ing updates. Repo contains both server and client configurations. But I don't want bot tokens (and maybe channel ids) to be widely available in configs. One way of doing so is not to commit tokens and manually add them back in to the server each time update occurs. But even with git stash it is somewhat tidious. 

It would be great to have an ability of specifying sensitive information through env variables like `DC_BOT_TOKEN`. This way it is a lot easier to provision updates to the server. Or even manage multiple instances of different servers running

_Sorry if this feature already exists. But i didn't found such possibility in quick start guide_

**Comment by ErdbeerbaerLP** [comment]
Add the config of the mod to an `.gitignore` file

**Comment by Malien** [comment]
Yep, I guess that is a solution. It would be nice to have a common config, and custom sensitive info. But that's no biggie.
