### ISSUE TITLE
[BUG] [1.12] SSP Save won't load after building Industrial Foregoing: Plant Interactor

### ISSUE THREAD

**Issue by MBfromOK** [ErdbeerbaerLP/Discord-Chat-Integration#82]
**What happened?**
- Tried to launch a SSP save after building Industrial Foregoing: Plant Interactor... 
- Game functions as expected during play time but then crashes when player attempts to load World at later date / time. (Tried 3x)

**What should happen?**
- World should load & spawn player

**Steps to reproduce**
- (Install Planetary Modpack)
- Place & enter a 13x13x13 Compact machine
- Plant Carrots / Potatoes
- Place a Plant Interactor (with range upgrades)
- Save World & Exit
- Relaunch world

**Version**
-
- [X] 1.12
- [ ] 1.14
- [ ] 1.15

Mod version 1.12.2-1.0.7

**Config file**
-# Configuration file

client {
    # Client ID of the Discord Rich Presence as seen in the developer portal
    S:"App ID"=<StuffNThingsGoHere>
    S:"Large Image Key"=bg
    S:"Small Image Key"=logo2
    S:"Small Image Text"=Planetary
}
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://paste.dimdev.org)**
- https://pastebin.com/3a8VQ4t9 - dimdev.org returned a 502 error

**Additional info**

- disabling the mod (added ".disabled" to filename) allows the world to load and player to spawn.

**Comment by ErdbeerbaerLP** [comment]
You are in the wrong bug tracker ;)

The one you wanted: https://github.com/TeamDman/Discord-Integration/issues (go here)

My mod: https://github.com/ErdbeerbaerLP/DiscordRichPresence/

And this is the bug tracker for the discord integration mod, which adds an Discord <-> Server chat bridge

**Comment by MBfromOK** [comment]
Thanks! Apparently today isn't my day... This was attempt 2 of apparently 3 to report the issue to the correct author... Thanks for your mod & time!
