### ISSUE TITLE
Is there a 1.7.10 repo?

### ISSUE THREAD

**Issue by jackowski626** [ErdbeerbaerLP/Discord-Chat-Integration#84]
I would like to add support for discord emojis (sent using emojicord mod), since discord bots need to use ids now for custom emojis. Would it be possible to get 1.7.10 source?

**Comment by ErdbeerbaerLP** [comment]
umm... there was never an 1.7 version, so I don't have any source code for 1.7

**Comment by jackowski626** [comment]
Sorry, must have confused with a other mod
