### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MacWhinny** [ErdbeerbaerLP/Discord-Chat-Integration#87]
**What happened?**
-Hello. I seem to have a heck of a lot of console spam when I start the server up or when shutting down, which makes the server take 2 to 5 times as long to start up/shut down. 

**What should happen?**
-

**Steps to reproduce**
- start the server up :D
- 

**Version**
-dcintegration-1.1.18-1.12

Mod version _0.0.0_

**Config file**
-https://bytebin.lucko.me/ejE9YkPtA9
*

**Crash report if available (use https://paste.dimdev.org)**
-https://gyazo.com/638e22de6ab784c2fedf80e44920bd4c

**Additional info**

-

**Comment by ErdbeerbaerLP** [comment]
Disable B:MODIFY_CHANNEL_DESCRIPTRION=true
See #70 for more information
