### ISSUE TITLE
Add the ability to see peoples FTBUtiltiies Ranks/Prefixes/Nicks

### ISSUE THREAD

**Issue by Osprey4444** [ErdbeerbaerLP/Discord-Chat-Integration#9]
As the title says (:

Is there any possibility of you adding a way of it allowing people to see peoples Ranks, Prefixes (That are added via ranks) and Nicknames set via /nick. Via Discord and Vice Versa if multiple bots are in one chat to enable Network Wide chat intergration?

Many thanks, you have made an amazing mod, thank you!

**Comment by ErdbeerbaerLP** [comment]
Will try to add this

**Comment by ErdbeerbaerLP** [comment]
If you want to update now, see https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/issues/11#issuecomment-546690404
Or wait till it is online on curseforge
