### ISSUE TITLE
[BUG] 1.3.2-1.16 crashes dedicated server Forge 1.16.1 build 32.0.70

### ISSUE THREAD

**Issue by kreezxil** [ErdbeerbaerLP/Discord-Chat-Integration#90]
Notes:
     NoSuchMethodError (probably a class change)

crash report: 
http://paste.ubuntu.com/p/q7pZQw2zBP/

fml server latest: 
http://paste.ubuntu.com/p/pYxQnqqk4d/

**Comment by vico93** [comment]
Confirmed on my side: Forge 32.0.71

**Comment by ErdbeerbaerLP** [comment]
Will try to fix that soon
