### ISSUE TITLE
[BUG] WARN RateLimiter - Encountered 429 on route

### ISSUE THREAD

**Issue by SamLam140330** [ErdbeerbaerLP/Discord-Chat-Integration#94]
**What happened?**
-
When I stop the server, it can't stop and loop the error of WARN RateLimiter - Encountered 429 on route /channels/742661929616539749
Full log can be found in: https://pastebin.com/wdkAYC6q

**What should happen?**
-
Close the server successfully

**Version**
-
- [x] 1.12
- [ ] 1.14
- [ ] 1.15

Mod version: _dcintegration-1.1.18_

**Config file**
-
https://pastebin.com/XA3TdCXB

**Comment by ErdbeerbaerLP** [comment]
Change
B:MODIFY_CHANNEL_DESCRIPTRION=true
To
B:MODIFY_CHANNEL_DESCRIPTRION=false
